import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '../../.orca/sql-check/node_modules/@electric-sql/pglite/dist/index.js';
const db = new PGlite();
const a='00000000-0000-4000-8000-000000000001', b='00000000-0000-4000-8000-000000000002', c='00000000-0000-4000-8000-000000000003';
const request=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const sql=await readFile(new URL('../migrations/20260920_nickname_changes.sql',import.meta.url),'utf8');
async function user(id,query,params=[],anonymous=false){await db.exec('SET ROLE authenticated');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false),set_config('test.anonymous',$2,false)",[id,String(anonymous)]);try{return (await db.query(query,params)).rows;}finally{await db.exec('RESET ROLE');}}
const state=async id=>(await user(id,'SELECT public.get_nickname_state_v1() s'))[0].s;
const rename=async(id,name,n,expected=id)=>(await user(id,'SELECT public.change_nickname_v1($1,$2,$3) s',[name,request(n),expected]))[0].s;
try{
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,raw_app_meta_data jsonb DEFAULT '{}'); CREATE TABLE auth.identities(user_id uuid REFERENCES auth.users(id),provider text);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT jsonb_build_object('is_anonymous',coalesce(nullif(current_setting('test.anonymous',true),''),'false')::boolean)$$;
 GRANT USAGE ON SCHEMA public,auth TO authenticated,anon,service_role;
 CREATE TABLE public.profiles(id uuid PRIMARY KEY REFERENCES auth.users(id),nickname text NOT NULL,updated_at timestamptz DEFAULT now());
 ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
 CREATE POLICY own ON public.profiles TO authenticated USING(id=auth.uid()) WITH CHECK(id=auth.uid());
 GRANT SELECT,INSERT,UPDATE ON public.profiles TO authenticated;
 INSERT INTO auth.users(id) VALUES('${a}'),('${b}'),('${c}'); INSERT INTO auth.identities VALUES('${a}','google'),('${b}','google'),('${c}','email');
 INSERT INTO public.profiles(id,nickname) VALUES('${a}','OldAlpha'),('${b}','Other'),('${c}','Email');`);
 await db.exec(sql);
 const d='00000000-0000-4000-8000-000000000004';
 await db.query("INSERT INTO auth.users(id,raw_app_meta_data) VALUES($1,'{\"provider\":\"google\"}')",[d]);
 await user(d,'INSERT INTO public.profiles(id,nickname) VALUES($1,$2)',[d,'Other']);
 assert.match((await db.query('SELECT nickname FROM public.profiles WHERE id=$1',[d])).rows[0].nickname,/^Player_/);
 assert.equal((await state(a)).free_available,true);assert.equal((await state(c)).free_available,false);
 const check=async name=>(await user(a,'SELECT public.check_nickname_v1($1) s',[name]))[0].s;
 assert.equal((await check(' other ')).code,'taken');assert.equal((await check('ＯＴＨＥＲ')).code,'taken');assert.equal((await check('a')).code,'invalid');
 await assert.rejects(user(a,'UPDATE public.profiles SET nickname=$1 WHERE id=$2',['Bypass',a]),/nickname_rpc_required/);
 await user(a,'UPDATE public.profiles SET nickname=nickname WHERE id=$1',[a]);
 assert.equal((await rename(a,'Ａｌｐｈａ',1)).nickname,'Alpha');assert.equal((await state(a)).free_available,false);
 assert.equal((await rename(a,'Alpha',1)).replayed,true);assert.equal((await rename(a,'Different',1)).code,'invalid');
 assert.equal((await rename(a,'Next',2)).code,'ticket_required');
 await assert.rejects(user(a,'SELECT public.grant_nickname_change_ticket_v1($1,$2,1)',[a,'fake-purchase']),/permission denied/);
 await db.exec('SET ROLE service_role');
 assert.equal((await db.query('SELECT public.grant_nickname_change_ticket_v1($1,$2,1) s',[a,'paid-1'])).rows[0].s.granted,true);
 assert.equal((await db.query('SELECT public.grant_nickname_change_ticket_v1($1,$2,1) s',[a,'paid-1'])).rows[0].s.granted,false);
 await assert.rejects(db.query('SELECT public.grant_nickname_change_ticket_v1($1,$2,1)',[b,'paid-1']),/purchase_conflict/);
 await db.exec('RESET ROLE');assert.equal((await state(a)).tickets,1);
 assert.equal((await rename(a,'Other',3)).code,'taken');assert.equal((await state(a)).tickets,1);
 await assert.rejects(rename(a,'Next',4,b),/account_changed/);assert.equal((await state(a)).tickets,1);
 assert.equal((await rename(a,'Next',5)).cost,'ticket');assert.equal((await state(a)).tickets,0);
 assert.equal((await rename(a,'Next',5)).replayed,true);assert.equal((await rename(a,'Next',6)).unchanged,true);
 await assert.rejects(user(a,'SELECT * FROM public.nickname_entitlements'),/permission denied/);
 await assert.rejects(user(a,'SELECT public.get_nickname_state_v1()',[],true),/authentication_required/);
 assert.equal((await rename(b,'Unique B',7)).cost,'free');assert.equal((await rename(b,'Second B',8)).code,'ticket_required');
 await db.exec(sql);assert.equal((await state(a)).free_available,false);assert.equal((await state(a)).tickets,0);
 await assert.rejects(db.query('UPDATE public.profiles SET nickname=$1 WHERE id=$2',['Ｎｅｘｔ',c]),/duplicate key/);
 console.log('PASS nickname SQL: normalized uniqueness, Google-only free once, direct-write denial, atomic ticket use, retries, unchanged/duplicate no charge, account binding, server-only idempotent grants, anonymous denial, migration rerun');
}finally{await db.close();}
