import type { LanguageCode } from "./i18n";
import { masteryCopy } from './mastery-ui';
import { bannerThemeName, bannerThemeCondition } from './banner-copy';
import { BANNER_IDS } from './banner-progress';
import type { BannerAppearance } from "./banner-collection";

export type CosmeticSlot =
  | "banner"
  | "frame"
  | "badge"
  | "badgeFrame"
  | "title"
  | "titleFrame";

export interface CosmeticLoadout {
  banner: BannerAppearance;
  frame: string | null;
  badge: string | null;
  badgeFrame: string | null;
  title: string | null;
  titleFrame: string | null;
}

export interface CosmeticCopyDict {
  slots: Record<CosmeticSlot, string>;
  slotDescriptions: Record<CosmeticSlot, string>;
  options: Record<string, string>;
  optionConditions: Record<string, string>;
  none: string;
  tabTitle: string;
  tabHint: string;
  previewHeading: string;
  previewSubheading: string;
  draftBadge: string;
  applyBtn: string;
  cancelBtn: string;
  appliedToast: string;
  guestNotice: string;
  guestBadge: string;
  lockedBadge: string;
  equippedBadge: string;
  devPreviewBadge: string;
  devPreviewNotice: string;
  badgeFrameHint: string;
  titleFrameHint: string;
  retryBtn: string;
}

const COSMETICS_COPY_DICTS: Record<LanguageCode, CosmeticCopyDict> = {
  ko: {
    slots: {
      banner: "배경",
      frame: "배경 테두리",
      badge: "배지",
      badgeFrame: "배지 테두리",
      title: "칭호",
      titleFrame: "칭호 테두리",
    },
    slotDescriptions: {
      banner: "배너의 기본 배경 일러스트를 선택합니다.",
      frame: "배경 외곽을 장식하는 프레임입니다.",
      badge: "왼쪽에 표시되는 상징 문양 배지입니다.",
      badgeFrame: "배지를 감싸는 금속 링 테두리입니다. 배지 표시 시 적용됩니다.",
      title: "닉네임 아래에 표시되는 플레이어 칭호입니다.",
      titleFrame: "칭호 플레이트를 감싸는 장식 테두리입니다. 칭호 표시 시 적용됩니다.",
    },
    options: {
      "classic": "클래식 골드",
      "slate": "슬레이트",
      "forest": "포레스트",
      "banner_cosmic_knight": "성운의 나이트",
      "banner_crimson_sun": "일도양단",
      "banner_hidden_myeongnyang": "불멸: 열두 척의 기적",
      "frame:classic-gold": "클래식 골드 프레임",
      "frame:mastery-complete": "마스터리 완전 정복",
      "badge:mastery-m01": "M01: 폰 숙련 배지",
      "badge:mastery-m02": "M02: 나이트 기동 배지",
      "badge:mastery-m03": "M03: 비숍 저격 배지",
      "badge:mastery-m04": "M04: 룩 돌파 배지",
      "badge:mastery-m05": "M05: 퀸 지배 배지",
      "badge:mastery-m06": "M06: 킹 수호 배지",
      "badge:mastery-m07": "M07: 전략의 대가",
      "badge:mastery-m08": "M08: 그랜드마스터",
      "badgeFrame:gold": "골드 링",
      "badgeFrame:silver": "실버 링",
      "badgeFrame:violet": "바이올렛 링",
      "title:challenger": "도전자",
      "title:explorer": "탐험가",
      "titleFrame:gold": "클래식 골드",
      "titleFrame:silver": "기사의 은빛",
      "titleFrame:violet": "보랏빛 문장",
    },
    optionConditions: {
      "classic": "회원 기본 제공",
      "slate": "회원 기본 제공",
      "forest": "회원 기본 제공",
      "banner_cosmic_knight": "나이트로 적 기물 50개 격추 (PvE)",
      "banner_crimson_sun": "1샷 3기물 동시 격추 (PvE)",
      "banner_hidden_myeongnyang": "열세 상황 대역전 승리 (스테이지 5+)",
      "frame:classic-gold": "회원 기본 제공",
      "frame:mastery-complete": "전 기물 마스터리 올 클리어",
      "badge:mastery-m01": "폰 마스터리 3성 달성",
      "badge:mastery-m02": "나이트 마스터리 3성 달성",
      "badge:mastery-m03": "비숍 마스터리 3성 달성",
      "badge:mastery-m04": "룩 마스터리 3성 달성",
      "badge:mastery-m05": "퀸 마스터리 3성 달성",
      "badge:mastery-m06": "킹 마스터리 3성 달성",
      "badge:mastery-m07": "전략 마스터리 3성 달성",
      "badge:mastery-m08": "모든 마스터리 정복",
      "badgeFrame:gold": "회원 기본 제공",
      "badgeFrame:silver": "회원 기본 제공",
      "badgeFrame:violet": "회원 기본 제공",
      "title:challenger": "회원 기본 제공",
      "title:explorer": "PvE 스테이지 10 클리어",
      "titleFrame:gold": "회원 기본 제공",
      "titleFrame:silver": "회원 기본 제공",
      "titleFrame:violet": "회원 기본 제공",
    },
    none: "없음 (미사용)",
    tabTitle: "외형 꾸미기",
    tabHint: "치장품 설정은 회원 계정에 즉시 동기화됩니다.",
    previewHeading: "배너 미리보기",
    previewSubheading: "6가지 독립 슬롯을 조합하여 나만의 배너를 완성하세요.",
    draftBadge: "미적용 변경사항",
    applyBtn: "적용하기",
    cancelBtn: "원래대로",
    appliedToast: "치장품 설정이 저장되었습니다.",
    guestNotice: "게스트는 기본 단색 배너를 사용합니다. 6종 외형 커스터마이징은 회원 로그인 후 이용할 수 있습니다.",
    guestBadge: "게스트 모드",
    lockedBadge: "잠김",
    equippedBadge: "장착 중",
    devPreviewBadge: "로컬 프리뷰",
    devPreviewNotice: "개발자 미리보기 모드입니다 (?bannerPreview=1). 모든 치장품이 잠금 해제되며 저장되지 않습니다.",
    badgeFrameHint: "배지를 켜면 선택한 배지 테두리가 함께 표시됩니다.",
    titleFrameHint: "칭호를 켜면 선택한 칭호 테두리가 함께 표시됩니다.",
    retryBtn: "다시 시도",
  },
  en: {
    slots: {
      banner: "Background",
      frame: "Banner Frame",
      badge: "Badge",
      badgeFrame: "Badge Frame",
      title: "Title",
      titleFrame: "Title Frame",
    },
    slotDescriptions: {
      banner: "Choose the main background illustration.",
      frame: "Outer frame decorating the banner edges.",
      badge: "Insignia medal displayed on the left.",
      badgeFrame: "Metallic ring bordering the badge. Visible when a badge is set.",
      title: "Honorary title shown beneath your nickname.",
      titleFrame: "Decorative plate frame surrounding your title.",
    },
    options: {
      "classic": "Classic Gold",
      "slate": "Slate",
      "forest": "Forest",
      "banner_cosmic_knight": "Cosmic Knight",
      "banner_crimson_sun": "Cleave in Two",
      "banner_hidden_myeongnyang": "Immortal: Twelve Ships",
      "frame:classic-gold": "Classic Gold Frame",
      "frame:mastery-complete": "Mastery Conquest Frame",
      "badge:mastery-m01": "M01: Pawn Mastery",
      "badge:mastery-m02": "M02: Knight Maneuver",
      "badge:mastery-m03": "M03: Bishop Sniper",
      "badge:mastery-m04": "M04: Rook Breakthrough",
      "badge:mastery-m05": "M05: Queen Dominion",
      "badge:mastery-m06": "M06: King Bastion",
      "badge:mastery-m07": "M07: Grand Strategist",
      "badge:mastery-m08": "M08: Grandmaster",
      "badgeFrame:gold": "Gold Ring",
      "badgeFrame:silver": "Silver Ring",
      "badgeFrame:violet": "Violet Ring",
      "title:challenger": "Challenger",
      "title:explorer": "Explorer",
      "titleFrame:gold": "Classic Gold",
      "titleFrame:silver": "Knight Silver",
      "titleFrame:violet": "Violet Crest",
    },
    optionConditions: {
      "classic": "Member default",
      "slate": "Member default",
      "forest": "Member default",
      "banner_cosmic_knight": "Knock off 50 enemy pieces with Knight (PvE)",
      "banner_crimson_sun": "Knock off 3+ enemies in one shot (PvE)",
      "banner_hidden_myeongnyang": "Win match from underdog deficit (Stage 5+)",
      "frame:classic-gold": "Member default",
      "frame:mastery-complete": "Complete all piece masteries",
      "badge:mastery-m01": "Achieve 3 stars in Pawn mastery",
      "badge:mastery-m02": "Achieve 3 stars in Knight mastery",
      "badge:mastery-m03": "Achieve 3 stars in Bishop mastery",
      "badge:mastery-m04": "Achieve 3 stars in Rook mastery",
      "badge:mastery-m05": "Achieve 3 stars in Queen mastery",
      "badge:mastery-m06": "Achieve 3 stars in King mastery",
      "badge:mastery-m07": "Achieve 3 stars in Strategy mastery",
      "badge:mastery-m08": "Conquer all masteries",
      "badgeFrame:gold": "Member default",
      "badgeFrame:silver": "Member default",
      "badgeFrame:violet": "Member default",
      "title:challenger": "Member default",
      "title:explorer": "Clear PvE Stage 10",
      "titleFrame:gold": "Member default",
      "titleFrame:silver": "Member default",
      "titleFrame:violet": "Member default",
    },
    none: "None (Disabled)",
    tabTitle: "Cosmetics",
    tabHint: "Cosmetic customizations sync directly to your account.",
    previewHeading: "Banner Preview",
    previewSubheading: "Mix and match 6 modular slots for your custom loadout.",
    draftBadge: "Unsaved Changes",
    applyBtn: "Apply",
    cancelBtn: "Reset",
    appliedToast: "Cosmetic loadout saved successfully.",
    guestNotice: "Guests use the standard solid banner. Log in with a member account to unlock 6-slot customization.",
    guestBadge: "Guest Mode",
    lockedBadge: "Locked",
    equippedBadge: "Equipped",
    devPreviewBadge: "Local Preview",
    devPreviewNotice: "Developer preview mode (?bannerPreview=1). All items unlocked, no persistence.",
    badgeFrameHint: "When a badge is equipped, the selected badge frame will also appear.",
    titleFrameHint: "When a title is equipped, the selected title frame will also appear.",
    retryBtn: "Retry Save",
  },
  ja: {
    slots: {
      banner: "背景",
      frame: "背景フレーム",
      badge: "バッジ",
      badgeFrame: "バッジ枠",
      title: "称号",
      titleFrame: "称号枠",
    },
    slotDescriptions: {
      banner: "バナーのメイン背景を選択します。",
      frame: "バナーの外枠を飾るフレームです。",
      badge: "左側に表示されるシンボルバッジです。",
      badgeFrame: "バッジを縁取る金属リングです。バッジ表示時に適用されます。",
      title: "プレイヤー名の下に表示される称号です。",
      titleFrame: "称号プレートを飾る装飾枠です。称号表示時に適用されます。",
    },
    options: {
      "classic": "クラシックゴールド",
      "slate": "スレート",
      "forest": "フォレスト",
      "banner_cosmic_knight": "星雲のナイト",
      "banner_crimson_sun": "一刀両断",
      "banner_hidden_myeongnyang": "不滅：十二隻の奇跡",
      "frame:classic-gold": "クラシックゴールド枠",
      "frame:mastery-complete": "マスタリー完全制覇",
      "badge:mastery-m01": "M01: ポーン熟練",
      "badge:mastery-m02": "M02: ナイト機動",
      "badge:mastery-m03": "M03: ビショップ狙撃",
      "badge:mastery-m04": "M04: ルーク突破",
      "badge:mastery-m05": "M05: クイーン支配",
      "badge:mastery-m06": "M06: キング守護",
      "badge:mastery-m07": "M07: 戦略の大家",
      "badge:mastery-m08": "M08: グランドマスター",
      "badgeFrame:gold": "ゴールドリング",
      "badgeFrame:silver": "シルバーリング",
      "badgeFrame:violet": "バイオレットリング",
      "title:challenger": "挑戦者",
      "title:explorer": "探検家",
      "titleFrame:gold": "クラシックゴールド",
      "titleFrame:silver": "騎士の銀光",
      "titleFrame:violet": "紫紺の紋章",
    },
    optionConditions: {
      "classic": "会員初期提供",
      "slate": "会員初期提供",
      "forest": "会員初期提供",
      "banner_cosmic_knight": "ナイトで敵駒50個撃破 (PvE)",
      "banner_crimson_sun": "1ショットで敵3個以上撃破 (PvE)",
      "banner_hidden_myeongnyang": "劣勢から大逆転勝利 (ステージ5+)",
      "frame:classic-gold": "会員初期提供",
      "frame:mastery-complete": "全駒マスタリー制覇",
      "badge:mastery-m01": "ポーンマスタリー★3達成",
      "badge:mastery-m02": "ナイトマスタリー★3達成",
      "badge:mastery-m03": "ビショップマスタリー★3達成",
      "badge:mastery-m04": "ルークマスタリー★3達成",
      "badge:mastery-m05": "クイーンマスタリー★3達成",
      "badge:mastery-m06": "キングマスタリー★3達成",
      "badge:mastery-m07": "戦略マスタリー★3達成",
      "badge:mastery-m08": "全マスタリー制覇",
      "badgeFrame:gold": "会員初期提供",
      "badgeFrame:silver": "会員初期提供",
      "badgeFrame:violet": "会員初期提供",
      "title:challenger": "会員初期提供",
      "title:explorer": "PvEステージ10クリア",
      "titleFrame:gold": "会員初期提供",
      "titleFrame:silver": "会員初期提供",
      "titleFrame:violet": "会員初期提供",
    },
    none: "なし (未設定)",
    tabTitle: "装飾設定",
    tabHint: "装飾設定は会員アカウントに自動保存されます。",
    previewHeading: "バナープレビュー",
    previewSubheading: "6つの独立スロットを組み合わせて独自のバナーを作成しましょう。",
    draftBadge: "未保存の変更",
    applyBtn: "適用する",
    cancelBtn: "元に戻す",
    appliedToast: "装飾設定が保存されました。",
    guestNotice: "ゲストは標準単色バナーを使用します。装飾の変更は会員ログイン後に利用可能です。",
    guestBadge: "ゲストモード",
    lockedBadge: "ロック中",
    equippedBadge: "装着中",
    devPreviewBadge: "ローカルプレビュー",
    devPreviewNotice: "開発用プレビューモードです (?bannerPreview=1)。全装飾が解放され保存は行われません。",
    badgeFrameHint: "バッジを設定すると、選択したバッジ枠も一緒に表示されます。",
    titleFrameHint: "称号を設定すると、選択した称号枠も一緒に表示されます。",
    retryBtn: "再試行",
  },
  "zh-CN": {
    slots: {
      banner: "背景",
      frame: "横幅边框",
      badge: "徽章",
      badgeFrame: "徽章边框",
      title: "称号",
      titleFrame: "称号边框",
    },
    slotDescriptions: {
      banner: "选择横幅的主题背景插图。",
      frame: "装饰横幅外缘的精致边框。",
      badge: "显示在左侧的专属象征徽章。",
      badgeFrame: "环绕徽章的金属环。开启徽章时生效。",
      title: "显示在昵称下方的荣誉称号。",
      titleFrame: "称号铭牌的装饰外框。开启称号时生效。",
    },
    options: {
      "classic": "经典金辉",
      "slate": "板岩灰",
      "forest": "静谧森林",
      "banner_cosmic_knight": "星云骑士",
      "banner_crimson_sun": "一刀两断",
      "banner_hidden_myeongnyang": "不灭：十二艘奇迹",
      "frame:classic-gold": "经典金色边框",
      "frame:mastery-complete": "全系精通征服框",
      "badge:mastery-m01": "M01: 兵熟练徽章",
      "badge:mastery-m02": "M02: 马机动徽章",
      "badge:mastery-m03": "M03: 象狙击徽章",
      "badge:mastery-m04": "M04: 车突破徽章",
      "badge:mastery-m05": "M05: 后统治徽章",
      "badge:mastery-m06": "M06: 王守护徽章",
      "badge:mastery-m07": "M07: 战略大师",
      "badge:mastery-m08": "M08: 特级大师",
      "badgeFrame:gold": "金色圆环",
      "badgeFrame:silver": "银色圆环",
      "badgeFrame:violet": "紫晶圆环",
      "title:challenger": "挑战者",
      "title:explorer": "探险家",
      "titleFrame:gold": "经典金框",
      "titleFrame:silver": "骑士银光",
      "titleFrame:violet": "紫罗兰纹章",
    },
    optionConditions: {
      "classic": "会员默认拥有",
      "slate": "会员默认拥有",
      "forest": "会员默认拥有",
      "banner_cosmic_knight": "使用骑士击落50个敌方棋子 (PvE)",
      "banner_crimson_sun": "单次击落3个以上敌方棋子 (PvE)",
      "banner_hidden_myeongnyang": "在劣势下逆转取胜 (第5关以上)",
      "frame:classic-gold": "会员默认拥有",
      "frame:mastery-complete": "完成全部棋子精通",
      "badge:mastery-m01": "兵精通达成3星",
      "badge:mastery-m02": "马精通达成3星",
      "badge:mastery-m03": "象精通达成3星",
      "badge:mastery-m04": "车精通达成3星",
      "badge:mastery-m05": "后精通达成3星",
      "badge:mastery-m06": "王精通达成3星",
      "badge:mastery-m07": "战略精通达成3星",
      "badge:mastery-m08": "全系精通达成",
      "badgeFrame:gold": "会员默认拥有",
      "badgeFrame:silver": "会员默认拥有",
      "badgeFrame:violet": "会员默认拥有",
      "title:challenger": "会员默认拥有",
      "title:explorer": "通关PvE第10关",
      "titleFrame:gold": "会员默认拥有",
      "titleFrame:silver": "会员默认拥有",
      "titleFrame:violet": "会员默认拥有",
    },
    none: "无 (未装备)",
    tabTitle: "个性装扮",
    tabHint: "装扮设置将即时同步保存至您的账号。",
    previewHeading: "横幅预览",
    previewSubheading: "自由搭配6个独立槽位，打造专属横幅。",
    draftBadge: "未保存更改",
    applyBtn: "应用",
    cancelBtn: "重置",
    appliedToast: "装扮配置已成功保存。",
    guestNotice: "游客使用标准单色横幅。登录会员账号后即可开启6槽装扮定制。",
    guestBadge: "游客模式",
    lockedBadge: "未解锁",
    equippedBadge: "已装备",
    devPreviewBadge: "本地预览",
    devPreviewNotice: "开发者预览模式 (?bannerPreview=1)，解锁所有项目且不保存。",
    badgeFrameHint: "装备徽章后，选择的徽章边框也会一并显示。",
    titleFrameHint: "装备称号后，选择的称号边框也会一并显示。",
    retryBtn: "重试保存",
  },
  de: {
    slots: {
      banner: "Hintergrund",
      frame: "Banner-Rahmen",
      badge: "Abzeichen",
      badgeFrame: "Abzeichen-Rahmen",
      title: "Titel",
      titleFrame: "Titel-Rahmen",
    },
    slotDescriptions: {
      banner: "Wähle das Haupt-Hintergrundbild.",
      frame: "Äußerer Rahmen zur Verzierung des Banners.",
      badge: "Abzeichen auf der linken Seite.",
      badgeFrame: "Metallring um das Abzeichen.",
      title: "Ehrentitel unter deinem Nicknamen.",
      titleFrame: "Dekorativer Rahmen um deinen Titel.",
    },
    options: {
      "classic": "Klassisches Gold",
      "slate": "Schiefer",
      "forest": "Wald",
      "banner_cosmic_knight": "Kosmischer Springer",
      "banner_crimson_sun": "Klingenschnitt",
      "banner_hidden_myeongnyang": "Unsterblich: Zwölf Schiffe",
      "frame:classic-gold": "Klassischer Goldrahmen",
      "frame:mastery-complete": "Meisterschafts-Eroberung",
      "badge:mastery-m01": "M01: Bauer-Meisterschaft",
      "badge:mastery-m02": "M02: Springer-Manöver",
      "badge:mastery-m03": "M03: Läufer-Präzision",
      "badge:mastery-m04": "M04: Turm-Durchbruch",
      "badge:mastery-m05": "M05: Dame-Herrschaft",
      "badge:mastery-m06": "M06: König-Bollwerk",
      "badge:mastery-m07": "M07: Groß-Stratege",
      "badge:mastery-m08": "M08: Großmeister",
      "badgeFrame:gold": "Goldener Ring",
      "badgeFrame:silver": "Silberner Ring",
      "badgeFrame:violet": "Violetter Ring",
      "title:challenger": "Herausforderer",
      "title:explorer": "Entdecker",
      "titleFrame:gold": "Klassisches Gold",
      "titleFrame:silver": "Ritter-Silber",
      "titleFrame:violet": "Violettes Wappen",
    },
    optionConditions: {
      "classic": "Mitglieder-Standard",
      "slate": "Mitglieder-Standard",
      "forest": "Mitglieder-Standard",
      "banner_cosmic_knight": "50 Figuren mit Springer abräumen (PvE)",
      "banner_crimson_sun": "3+ Figuren mit 1 Schuss abräumen (PvE)",
      "banner_hidden_myeongnyang": "Aus Rückstand siegen (Stufe 5+)",
      "frame:classic-gold": "Mitglieder-Standard",
      "frame:mastery-complete": "Alle Figuren-Meisterschaften abschließen",
      "badge:mastery-m01": "Bauer-Meisterschaft 3 Sterne",
      "badge:mastery-m02": "Springer-Meisterschaft 3 Sterne",
      "badge:mastery-m03": "Läufer-Meisterschaft 3 Sterne",
      "badge:mastery-m04": "Turm-Meisterschaft 3 Sterne",
      "badge:mastery-m05": "Dame-Meisterschaft 3 Sterne",
      "badge:mastery-m06": "König-Meisterschaft 3 Sterne",
      "badge:mastery-m07": "Strategie-Meisterschaft 3 Sterne",
      "badge:mastery-m08": "Alle Meisterschaften bezwingen",
      "badgeFrame:gold": "Mitglieder-Standard",
      "badgeFrame:silver": "Mitglieder-Standard",
      "badgeFrame:violet": "Mitglieder-Standard",
      "title:challenger": "Mitglieder-Standard",
      "title:explorer": "PvE Stufe 10 abschließen",
      "titleFrame:gold": "Mitglieder-Standard",
      "titleFrame:silver": "Mitglieder-Standard",
      "titleFrame:violet": "Mitglieder-Standard",
    },
    none: "Keine (Deaktiviert)",
    tabTitle: "Kosmetik",
    tabHint: "Kosmetische Einstellungen werden im Konto gespeichert.",
    previewHeading: "Banner-Vorschau",
    previewSubheading: "Kombiniere 6 modulare Slots für dein persönliches Banner.",
    draftBadge: "Ungespeicherte Änderungen",
    applyBtn: "Anwenden",
    cancelBtn: "Zurücksetzen",
    appliedToast: "Kosmetik erfolgreich gespeichert.",
    guestNotice: "Gäste nutzen das Standard-Banner. Melde dich an, um alle 6 Slots anzupassen.",
    guestBadge: "Gastmodus",
    lockedBadge: "Gesperrt",
    equippedBadge: "Ausrüstet",
    devPreviewBadge: "Lokale Vorschau",
    devPreviewNotice: "Entwicklervorschau (?bannerPreview=1). Alles freigeschaltet, keine Speicherung.",
    badgeFrameHint: "Wenn ein Abzeichen aktiv ist, wird der gewählte Rahmen angezeigt.",
    titleFrameHint: "Wenn ein Titel aktiv ist, wird der gewählte Rahmen angezeigt.",
    retryBtn: "Erneut versuchen",
  },
  fr: {
    slots: {
      banner: "Arrière-plan",
      frame: "Cadre de bannière",
      badge: "Badge",
      badgeFrame: "Cadre de badge",
      title: "Titre",
      titleFrame: "Cadre de titre",
    },
    slotDescriptions: {
      banner: "Choisissez l'illustration d'arrière-plan principale.",
      frame: "Cadre décoratif extérieur entourant la bannière.",
      badge: "Médaille d'insigne affichée sur la gauche.",
      badgeFrame: "Anneau métallique entourant le badge.",
      title: "Titre honorifique affiché sous votre pseudonyme.",
      titleFrame: "Cadre décoratif autour de votre plaque de titre.",
    },
    options: {
      "classic": "Or classique",
      "slate": "Ardoise",
      "forest": "Forêt",
      "banner_cosmic_knight": "Cavalier cosmique",
      "banner_crimson_sun": "Tranchant net",
      "banner_hidden_myeongnyang": "Immortel : Douze navires",
      "frame:classic-gold": "Cadre or classique",
      "frame:mastery-complete": "Conquête de maîtrise",
      "badge:mastery-m01": "M01: Maîtrise Pion",
      "badge:mastery-m02": "M02: Manœuvre Cavalier",
      "badge:mastery-m03": "M03: Sniper Fou",
      "badge:mastery-m04": "M04: Percée Tour",
      "badge:mastery-m05": "M05: Domination Dame",
      "badge:mastery-m06": "M06: Bastion Roi",
      "badge:mastery-m07": "M07: Grand Stratège",
      "badge:mastery-m08": "M08: Grand Maître",
      "badgeFrame:gold": "Anneau d'or",
      "badgeFrame:silver": "Anneau d'argent",
      "badgeFrame:violet": "Anneau violet",
      "title:challenger": "Challenger",
      "title:explorer": "Explorateur",
      "titleFrame:gold": "Or classique",
      "titleFrame:silver": "Argent de chevalier",
      "titleFrame:violet": "Blason violet",
    },
    optionConditions: {
      "classic": "Par défaut membre",
      "slate": "Par défaut membre",
      "forest": "Par défaut membre",
      "banner_cosmic_knight": "Éjecter 50 pièces avec le cavalier (PvE)",
      "banner_crimson_sun": "Éjecter 3+ pièces en 1 tir (PvE)",
      "banner_hidden_myeongnyang": "Gagner après infériorité numérique (Étape 5+)",
      "frame:classic-gold": "Par défaut membre",
      "frame:mastery-complete": "Compléter toutes les maîtrises de pièces",
      "badge:mastery-m01": "Pion 3 étoiles",
      "badge:mastery-m02": "Cavalier 3 étoiles",
      "badge:mastery-m03": "Fou 3 étoiles",
      "badge:mastery-m04": "Tour 3 étoiles",
      "badge:mastery-m05": "Dame 3 étoiles",
      "badge:mastery-m06": "Roi 3 étoiles",
      "badge:mastery-m07": "Stratégie 3 étoiles",
      "badge:mastery-m08": "Toutes les maîtrises conquises",
      "badgeFrame:gold": "Par défaut membre",
      "badgeFrame:silver": "Par défaut membre",
      "badgeFrame:violet": "Par défaut membre",
      "title:challenger": "Par défaut membre",
      "title:explorer": "Terminer l'étape 10 PvE",
      "titleFrame:gold": "Par défaut membre",
      "titleFrame:silver": "Par défaut membre",
      "titleFrame:violet": "Par défaut membre",
    },
    none: "Aucun (Désactivé)",
    tabTitle: "Cosmétiques",
    tabHint: "Les réglages cosmétiques sont synchronisés sur votre compte.",
    previewHeading: "Aperçu de la bannière",
    previewSubheading: "Combinez 6 emplacements modulaires pour personnaliser votre bannière.",
    draftBadge: "Modifications non enregistrées",
    applyBtn: "Appliquer",
    cancelBtn: "Réinitialiser",
    appliedToast: "Cosmétiques enregistrés avec succès.",
    guestNotice: "Les invités utilisent la bannière unie. Connectez-vous pour déverrouiller la personnalisation à 6 slots.",
    guestBadge: "Mode Invité",
    lockedBadge: "Verrouillé",
    equippedBadge: "Équipé",
    devPreviewBadge: "Aperçu Local",
    devPreviewNotice: "Mode aperçu développeur (?bannerPreview=1). Tout déverrouillé, sans sauvegarde.",
    badgeFrameHint: "Quand un badge est activé, son cadre sélectionné apparaît aussi.",
    titleFrameHint: "Quand un titre est activé, son cadre sélectionné apparaît aussi.",
    retryBtn: "Réessayer",
  },
  es: {
    slots: {
      banner: "Fondo",
      frame: "Marco de estandarte",
      badge: "Insignia",
      badgeFrame: "Marco de insignia",
      title: "Título",
      titleFrame: "Marco de título",
    },
    slotDescriptions: {
      banner: "Elige la ilustración de fondo principal.",
      frame: "Marco decorativo exterior del estandarte.",
      badge: "Medalla conmemorativa en el lado izquierdo.",
      badgeFrame: "Anillo metálico que rodea la insignia.",
      title: "Título honorífico bajo tu nombre de jugador.",
      titleFrame: "Marco decorativo para la placa de título.",
    },
    options: {
      "classic": "Oro clásico",
      "slate": "Pizarra",
      "forest": "Bosque",
      "banner_cosmic_knight": "Caballo Cósmico",
      "banner_crimson_sun": "Corte Limpio",
      "banner_hidden_myeongnyang": "Inmortal: Doce Naves",
      "frame:classic-gold": "Marco de oro clásico",
      "frame:mastery-complete": "Conquista de maestría",
      "badge:mastery-m01": "M01: Maestría de Peón",
      "badge:mastery-m02": "M02: Maniobra de Caballo",
      "badge:mastery-m03": "M03: Francotirador Alfil",
      "badge:mastery-m04": "M04: Ruptura de Torre",
      "badge:mastery-m05": "M05: Dominio de Reina",
      "badge:mastery-m06": "M06: Bastión de Rey",
      "badge:mastery-m07": "M07: Gran Estratega",
      "badge:mastery-m08": "M08: Gran Maestro",
      "badgeFrame:gold": "Anillo de oro",
      "badgeFrame:silver": "Anillo de plata",
      "badgeFrame:violet": "Anillo violeta",
      "title:challenger": "Aspirante",
      "title:explorer": "Explorador",
      "titleFrame:gold": "Oro clásico",
      "titleFrame:silver": "Plata de caballero",
      "titleFrame:violet": "Blasón violeta",
    },
    optionConditions: {
      "classic": "Por defecto miembro",
      "slate": "Por defecto miembro",
      "forest": "Por defecto miembro",
      "banner_cosmic_knight": "Expulsa 50 piezas con Caballo (PvE)",
      "banner_crimson_sun": "Expulsa 3+ piezas en 1 tiro (PvE)",
      "banner_hidden_myeongnyang": "Remonta en desventaja y gana (Fase 5+)",
      "frame:classic-gold": "Por defecto miembro",
      "frame:mastery-complete": "Completa todas las maestrías de piezas",
      "badge:mastery-m01": "Peón 3 estrellas",
      "badge:mastery-m02": "Caballo 3 estrellas",
      "badge:mastery-m03": "Alfil 3 estrellas",
      "badge:mastery-m04": "Torre 3 estrellas",
      "badge:mastery-m05": "Reina 3 estrellas",
      "badge:mastery-m06": "Rey 3 estrellas",
      "badge:mastery-m07": "Estrategia 3 estrellas",
      "badge:mastery-m08": "Todas las maestrías completadas",
      "badgeFrame:gold": "Por defecto miembro",
      "badgeFrame:silver": "Por defecto miembro",
      "badgeFrame:violet": "Por defecto miembro",
      "title:challenger": "Por defecto miembro",
      "title:explorer": "Supera la fase 10 PvE",
      "titleFrame:gold": "Por defecto miembro",
      "titleFrame:silver": "Por defecto miembro",
      "titleFrame:violet": "Por defecto miembro",
    },
    none: "Ninguno (Desactivado)",
    tabTitle: "Cosméticos",
    tabHint: "Los ajustes cosméticos se guardan en tu cuenta.",
    previewHeading: "Vista previa del estandarte",
    previewSubheading: "Combina 6 ranuras modulares para personalizar tu estandarte.",
    draftBadge: "Cambios sin guardar",
    applyBtn: "Aplicar",
    cancelBtn: "Restablecer",
    appliedToast: "Cosméticos guardados correctamente.",
    guestNotice: "Los invitados usan el estandarte liso estándar. Inicia sesión para personalizar las 6 ranuras.",
    guestBadge: "Modo Invitado",
    lockedBadge: "Bloqueado",
    equippedBadge: "Equipado",
    devPreviewBadge: "Vista Previa Local",
    devPreviewNotice: "Modo vista previa para desarrolladores (?bannerPreview=1). Todo desbloqueado sin guardar.",
    badgeFrameHint: "Al activar una insignia, también se mostrará el marco seleccionado.",
    titleFrameHint: "Al activar un título, también se mostrará el marco seleccionado.",
    retryBtn: "Reintentar",
  },
  ru: {
    slots: {
      banner: "Фон",
      frame: "Рамка баннера",
      badge: "Значок",
      badgeFrame: "Оправа значка",
      title: "Титул",
      titleFrame: "Оправа титула",
    },
    slotDescriptions: {
      banner: "Выберите основную фоновую иллюстрацию.",
      frame: "Внешняя декоративная рамка баннера.",
      badge: "Символический значок слева.",
      badgeFrame: "Металлическое кольцо вокруг значка.",
      title: "Почетный титул под вашим именем.",
      titleFrame: "Декоративная рамка вокруг титула.",
    },
    options: {
      "classic": "Классическое золото",
      "slate": "Сланец",
      "forest": "Лес",
      "banner_cosmic_knight": "Космический конь",
      "banner_crimson_sun": "Рассечение",
      "banner_hidden_myeongnyang": "Бессмертие: Двенадцать кораблей",
      "frame:classic-gold": "Классическая золотая рамка",
      "frame:mastery-complete": "Триумф мастерства",
      "badge:mastery-m01": "M01: Мастерство пешки",
      "badge:mastery-m02": "M02: Маневр коня",
      "badge:mastery-m03": "M03: Снайпер-слон",
      "badge:mastery-m04": "M04: Прорыв ладьи",
      "badge:mastery-m05": "M05: Власть ферзя",
      "badge:mastery-m06": "M06: Оплот короля",
      "badge:mastery-m07": "M07: Великий стратег",
      "badge:mastery-m08": "M08: Гроссмейстер",
      "badgeFrame:gold": "Золотое кольцо",
      "badgeFrame:silver": "Серебряное кольцо",
      "badgeFrame:violet": "Фиолетовое кольцо",
      "title:challenger": "Претендент",
      "title:explorer": "Исследователь",
      "titleFrame:gold": "Классическое золото",
      "titleFrame:silver": "Рыцарское серебро",
      "titleFrame:violet": "Пурпурный герб",
    },
    optionConditions: {
      "classic": "По умолчанию для участников",
      "slate": "По умолчанию для участников",
      "forest": "По умолчанию для участников",
      "banner_cosmic_knight": "Выбить 50 вражеских фигур конем (PvE)",
      "banner_crimson_sun": "Выбить 3+ фигуры за один удар (PvE)",
      "banner_hidden_myeongnyang": "Победить при численном меньшинстве (Этап 5+)",
      "frame:classic-gold": "По умолчанию для участников",
      "frame:mastery-complete": "Завершить мастерство всех фигур",
      "badge:mastery-m01": "Пешка: 3 звезды",
      "badge:mastery-m02": "Конь: 3 звезды",
      "badge:mastery-m03": "Слон: 3 звезды",
      "badge:mastery-m04": "Ладья: 3 звезды",
      "badge:mastery-m05": "Ферзь: 3 звезды",
      "badge:mastery-m06": "Король: 3 звезды",
      "badge:mastery-m07": "Стратегия: 3 звезды",
      "badge:mastery-m08": "Все мастерства покорены",
      "badgeFrame:gold": "По умолчанию для участников",
      "badgeFrame:silver": "По умолчанию для участников",
      "badgeFrame:violet": "По умолчанию для участников",
      "title:challenger": "По умолчанию для участников",
      "title:explorer": "Пройти 10 этап PvE",
      "titleFrame:gold": "По умолчанию для участников",
      "titleFrame:silver": "По умолчанию для участников",
      "titleFrame:violet": "По умолчанию для участников",
    },
    none: "Нет (Отключено)",
    tabTitle: "Оформление",
    tabHint: "Настройки оформления синхронизируются с вашей учетной записью.",
    previewHeading: "Предпросмотр баннера",
    previewSubheading: "Комбинируйте 6 слотов для создания уникального баннера.",
    draftBadge: "Несохраненные изменения",
    applyBtn: "Применить",
    cancelBtn: "Сбросить",
    appliedToast: "Настройки оформления сохранены.",
    guestNotice: "Гости используют стандартный баннер. Войдите в аккаунт для 6-слотовой настройки.",
    guestBadge: "Режим гостя",
    lockedBadge: "Заблокировано",
    equippedBadge: "Надето",
    devPreviewBadge: "Локальный предпросмотр",
    devPreviewNotice: "Режим разработчика (?bannerPreview=1). Всё открыто, без сохранения.",
    badgeFrameHint: "При включении значка выбранная оправа также отобразится.",
    titleFrameHint: "При включении титула выбранная оправа также отобразится.",
    retryBtn: "Повторить",
  },
  "pt-BR": {
    slots: {
      banner: "Fundo",
      frame: "Moldura do Banner",
      badge: "Emblema",
      badgeFrame: "Moldura do Emblema",
      title: "Título",
      titleFrame: "Moldura do Título",
    },
    slotDescriptions: {
      banner: "Escolha a ilustração principal de fundo.",
      frame: "Moldura externa decorativa do banner.",
      badge: "Medalha de insígnia exibida à esquerda.",
      badgeFrame: "Anel metálico ao redor do emblema.",
      title: "Título honorário exibido abaixo do seu apelido.",
      titleFrame: "Moldura decorativa da placa do título.",
    },
    options: {
      "classic": "Ouro Clássico",
      "slate": "Ardósia",
      "forest": "Floresta",
      "banner_cosmic_knight": "Cavaleiro Cósmico",
      "banner_crimson_sun": "Golpe Preciso",
      "banner_hidden_myeongnyang": "Imortal: Doze Navios",
      "frame:classic-gold": "Moldura Ouro Clássico",
      "frame:mastery-complete": "Conquista de Maestria",
      "badge:mastery-m01": "M01: Maestria de Peão",
      "badge:mastery-m02": "M02: Manobra de Cavalo",
      "badge:mastery-m03": "M03: Precisão de Bispo",
      "badge:mastery-m04": "M04: Ruptura de Torre",
      "badge:mastery-m05": "M05: Domínio de Rainha",
      "badge:mastery-m06": "M06: Bastião de Rei",
      "badge:mastery-m07": "M07: Grão-Estrategista",
      "badge:mastery-m08": "M08: Grande Mestre",
      "badgeFrame:gold": "Anel de Ouro",
      "badgeFrame:silver": "Anel de Prata",
      "badgeFrame:violet": "Anel Violeta",
      "title:challenger": "Desafiante",
      "title:explorer": "Explorador",
      "titleFrame:gold": "Ouro Clássico",
      "titleFrame:silver": "Prata do Cavaleiro",
      "titleFrame:violet": "Brasão Violeta",
    },
    optionConditions: {
      "classic": "Padrão de membro",
      "slate": "Padrão de membro",
      "forest": "Padrão de membro",
      "banner_cosmic_knight": "Derrube 50 peças com Cavalo (PvE)",
      "banner_crimson_sun": "Derrube 3+ peças em 1 tiro (PvE)",
      "banner_hidden_myeongnyang": "Vença em desvantagem numérica (Fase 5+)",
      "frame:classic-gold": "Padrão de membro",
      "frame:mastery-complete": "Conclua a maestria de todas as peças",
      "badge:mastery-m01": "Peão 3 estrelas",
      "badge:mastery-m02": "Cavalo 3 estrelas",
      "badge:mastery-m03": "Bispo 3 estrelas",
      "badge:mastery-m04": "Torre 3 estrelas",
      "badge:mastery-m05": "Rainha 3 estrelas",
      "badge:mastery-m06": "Rei 3 estrelas",
      "badge:mastery-m07": "Estratégia 3 estrelas",
      "badge:mastery-m08": "Todas as maestrias conquistadas",
      "badgeFrame:gold": "Padrão de membro",
      "badgeFrame:silver": "Padrão de membro",
      "badgeFrame:violet": "Padrão de membro",
      "title:challenger": "Padrão de membro",
      "title:explorer": "Conclua a Fase 10 PvE",
      "titleFrame:gold": "Padrão de membro",
      "titleFrame:silver": "Padrão de membro",
      "titleFrame:violet": "Padrão de membro",
    },
    none: "Nenhum (Desativado)",
    tabTitle: "Cosméticos",
    tabHint: "As opções cosméticas são sincronizadas diretamente na sua conta.",
    previewHeading: "Prévia do Banner",
    previewSubheading: "Combine 6 espaços modulares para criar seu banner exclusivo.",
    draftBadge: "Alterações não salvas",
    applyBtn: "Aplicar",
    cancelBtn: "Restaurar",
    appliedToast: "Cosméticos salvos com sucesso.",
    guestNotice: "Visitantes usam o banner liso padrão. Entre com uma conta para desbloquear a personalização em 6 slots.",
    guestBadge: "Modo Visitante",
    lockedBadge: "Bloqueado",
    equippedBadge: "Equipado",
    devPreviewBadge: "Prévia Local",
    devPreviewNotice: "Modo de prévia de desenvolvimento (?bannerPreview=1). Tudo liberado sem salvar.",
    badgeFrameHint: "Ao equipar um emblema, a moldura escolhida também será exibida.",
    titleFrameHint: "Ao equipar um título, a moldura escolhida também será exibida.",
    retryBtn: "Tentar novamente",
  },
};

export function getCosmeticsCopy(lang?: LanguageCode): CosmeticCopyDict {
  const code = (lang || "en") as LanguageCode;
  const base = COSMETICS_COPY_DICTS[code] || COSMETICS_COPY_DICTS.en;
  const copy = { ...base, options: { ...base.options }, optionConditions: { ...base.optionConditions } };
  const mastery = masteryCopy(code);
  for (const [id, name] of Object.entries(mastery.names)) {
    const key = `badge:mastery-${id.toLowerCase()}`;
    copy.options[key] = name;
    copy.optionConditions[key] = mastery.conditions[id as keyof typeof mastery.names];
  }
  for (const id of BANNER_IDS) {
    copy.options[id] = bannerThemeName(id, code);
    copy.optionConditions[id] = bannerThemeCondition(id, code);
  }
  const milestones = {
    ko: ['숙련도 메달 4개 달성', '숙련도 메달 8개 달성'], en: ['Earn 4 mastery medals', 'Earn 8 mastery medals'],
    ja: ['熟練度メダルを4個獲得', '熟練度メダルを8個獲得'], 'zh-CN': ['获得4枚熟练度奖章', '获得8枚熟练度奖章'],
    de: ['4 Meisterschaftsmedaillen verdienen', '8 Meisterschaftsmedaillen verdienen'], fr: ['Obtenir 4 médailles de maîtrise', 'Obtenir 8 médailles de maîtrise'],
    es: ['Consigue 4 medallas de maestría', 'Consigue 8 medallas de maestría'], ru: ['Получите 4 медали мастерства', 'Получите 8 медалей мастерства'],
    'pt-BR': ['Obtenha 4 medalhas de maestria', 'Obtenha 8 medalhas de maestria'],
  };
  copy.optionConditions['title:explorer'] = milestones[code][0];
  copy.optionConditions['frame:mastery-complete'] = milestones[code][1];
  copy.equippedBadge = { ko: '선택됨', en: 'Selected', ja: '選択中', 'zh-CN': '已选择', de: 'Ausgewählt', fr: 'Sélectionné', es: 'Seleccionado', ru: 'Выбрано', 'pt-BR': 'Selecionado' }[code];
  return copy;
}
