import type { PieceType } from "./config";
import { I18nManager, type LanguageCode } from "./i18n";

const TEXTS: Record<LanguageCode, Record<string, string>> = {
  ko: {
    strategyTitle: "전략 덱", strategyDescription: "전략 포인트 총 10점 · 항목당 최대 4점 · 전략 포인트 1점마다 힘 또는 중량 +2%",
    researchTitle: "기물 연구", researchDescription: "기초 연구 → 전체 크기 → 심화 연구 순서로 강화합니다.",
    allocated: "전략 포인트", pointsHeld: "연구 포인트", remaining: "남음", current: "현재 최종 효과", next: "다음 최종 효과",
    level: "단계", cost: "비용", maximum: "최대 단계입니다.", budgetSpent: "전략 포인트 10점을 모두 배분했습니다. 다른 항목에서 점수를 빼세요.",
    minimum: "더 이상 줄일 수 없습니다.", insufficientPoints: "연구 포인트가 부족합니다.",
    advancedLocked: "전체 크기 연구를 구매하면 심화 연구가 열립니다.",
    kingBasicLocked: "폰과 나이트의 기초 힘·중량을 모두 3단계까지 연구하세요.",
    queenBasicLocked: "룩과 비숍의 기초 힘·중량을 모두 3단계까지 연구하세요.",
    kingAdvancedLocked: "폰과 나이트의 심화 힘·중량을 모두 3단계까지 연구하세요.",
    queenAdvancedLocked: "룩과 비숍의 심화 힘·중량을 모두 3단계까지 연구하세요.",
    sizeLocked: "여섯 말의 기초 힘·중량을 모두 3단계까지 연구하세요.",
    sizeDescription: "내 모든 말의 실제 크기 +5% · 심화 연구 해금", size: "전체 크기",
    increase: "늘리기", decrease: "줄이기", buy: "연구하기", preview: "3D 미리보기", previewHint: "좌우로 드래그해 회전",
    resetView: "시점 초기화", previewUnavailable: "3D 미리보기를 사용할 수 없습니다. 강화와 배분은 계속할 수 있습니다.",
    previewLoading: "3D 미리보기 준비 중", researchNoDecrease: "연구는 개별 감소할 수 없습니다. 전체 초기화를 이용하세요.",
    allocationSaved: "전략 포인트 배분을 저장했습니다.", allocationReset: "전략 포인트 배분을 초기화했습니다.",
    storageUnavailable: "전략 포인트 배분은 적용했지만 이 브라우저에 저장하지 못했습니다.",
    purchaseSuccess: "연구를 완료했습니다.", purchaseFailed: "연구를 구매하지 못했습니다.", researchReset: "연구를 초기화하고 연구 포인트를 전액 반환했습니다.",
    resetAllocation: "전략 포인트 배분 초기화", resetResearch: "연구 전체 초기화", findMatch: "전략 대국 찾기",
    confirm: "확인", cancel: "취소", resetQuestion: "모든 연구를 초기화할까요? 반환 연구 포인트:",
    unspentQuestion: "아직 배분하지 않은 전략 포인트가 있습니다. 이 덱으로 대국을 찾을까요? 남은 전략 포인트:",
    actionFailed: "요청을 완료하지 못했습니다. 잠시 후 다시 시도하세요.", basic: "기초 연구", advanced: "심화 연구", locked: "잠김",
    force: "힘", weight: "중량", pieceList: "말 선택",
  },
  en: {
    strategyTitle: "Strategy Deck", strategyDescription: "Total 10 Strategy Points · Max 4 per stat · +2% Force or Weight per point",
    researchTitle: "Piece Research", researchDescription: "Research in order: Basic Research → Overall Size → Advanced Research.",
    allocated: "Strategy Points", pointsHeld: "Research Points", remaining: "Remaining", current: "Current Effect", next: "Next Effect",
    level: "Level", cost: "Cost", maximum: "Max level reached.", budgetSpent: "All 10 strategy points allocated. Deduct points from another stat.",
    minimum: "Cannot reduce further.", insufficientPoints: "Not enough research points.",
    advancedLocked: "Purchase Overall Size research to unlock Advanced research.",
    kingBasicLocked: "Research Basic Force & Weight for Pawn & Knight to Lv.3.",
    queenBasicLocked: "Research Basic Force & Weight for Rook & Bishop to Lv.3.",
    kingAdvancedLocked: "Research Advanced Force & Weight for Pawn & Knight to Lv.3.",
    queenAdvancedLocked: "Research Advanced Force & Weight for Rook & Bishop to Lv.3.",
    sizeLocked: "Research Basic Force & Weight for all 6 pieces to Lv.3.",
    sizeDescription: "All pieces physical size +5% · Unlocks Advanced research", size: "Overall Size",
    increase: "Increase", decrease: "Decrease", buy: "Research", preview: "3D Preview", previewHint: "Drag left/right to rotate",
    resetView: "Reset View", previewUnavailable: "3D preview unavailable. Upgrades and allocation can still be done.",
    previewLoading: "Loading 3D preview...", researchNoDecrease: "Cannot decrease individual research. Use Full Reset.",
    allocationSaved: "Strategy point allocation saved.", allocationReset: "Strategy point allocation reset.",
    storageUnavailable: "Strategy point allocation applied but failed to save in browser.",
    purchaseSuccess: "Research completed.", purchaseFailed: "Failed to purchase research.", researchReset: "Research reset and all research points refunded.",
    resetAllocation: "Reset Strategy Allocation", resetResearch: "Reset All Research", findMatch: "Find Strategy Match",
    confirm: "Confirm", cancel: "Cancel", resetQuestion: "Reset all research? Refund research points:",
    unspentQuestion: "You have unspent strategy points. Find match with this deck? Remaining strategy points:",
    actionFailed: "Request failed. Please try again shortly.", basic: "Basic Research", advanced: "Advanced Research", locked: "Locked",
    force: "Force", weight: "Weight", pieceList: "Select Piece",
  },
  ja: {
    strategyTitle: "戦略デッキ", strategyDescription: "戦略ポイント合計10P · 項目最大4P · 戦略ポイント1Pごとに力または重量+2%",
    researchTitle: "駒の研究", researchDescription: "基礎研究 → 全体サイズ → 応用研究の順で強化します。",
    allocated: "戦略ポイント", pointsHeld: "研究ポイント", remaining: "残り", current: "現在の効果", next: "次の効果",
    level: "段階", cost: "コスト", maximum: "最大段階です。", budgetSpent: "戦略ポイントを10Pすべて配分しました。他の項目から引いてください。",
    minimum: "これ以上減らせません。", insufficientPoints: "研究ポイントが不足しています。",
    advancedLocked: "全体サイズ研究を購入すると応用研究が解放されます。",
    kingBasicLocked: "ポーンとナイトの基礎力・重量を両方Lv.3まで研究してください。",
    queenBasicLocked: "ルークとビショップの基礎力・重量を両方Lv.3まで研究してください。",
    kingAdvancedLocked: "ポーンとナイトの応用力・重量を両方Lv.3まで研究してください。",
    queenAdvancedLocked: "ルークとビショップの応用力・重量を両方Lv.3まで研究してください。",
    sizeLocked: "全6駒の基礎力・重量をすべてLv.3まで研究してください。",
    sizeDescription: "全自駒のサイズ+5% · 応用研究を解放", size: "全体サイズ",
    increase: "増やす", decrease: "減らす", buy: "研究する", preview: "3Dプレビュー", previewHint: "左右にドラッグして回転",
    resetView: "視点リセット", previewUnavailable: "3Dプレビューを利用できません。強化と配分は続けられます。",
    previewLoading: "3Dプレビュー準備中", researchNoDecrease: "個別の研究減少はできません。全体初期化をご利用ください。",
    allocationSaved: "戦略ポイントの配分を保存しました。", allocationReset: "戦略ポイントの配分をリセットしました。",
    storageUnavailable: "戦略ポイントの配分は適用されましたがブラウザへの保存に失敗しました。",
    purchaseSuccess: "研究が完了しました。", purchaseFailed: "研究の購入に失敗しました。", researchReset: "研究をリセットし研究ポイントを全額返還しました。",
    resetAllocation: "戦略ポイント配分リセット", resetResearch: "研究全初期化", findMatch: "戦略対局を探す",
    confirm: "確認", cancel: "キャンセル", resetQuestion: "すべての研究をリセットしますか？ 返還研究ポイント:",
    unspentQuestion: "未配分の戦略ポイントがあります。このデッキで対局を探しますか？ 残り戦略ポイント:",
    actionFailed: "リクエストに失敗しました。しばらくしてから再試行してください。", basic: "基礎研究", advanced: "応用研究", locked: "ロック",
    force: "力", weight: "重量", pieceList: "駒選択",
  },
  "zh-CN": {
    strategyTitle: "策略卡组", strategyDescription: "策略点数共10点 · 单项上限4点 · 每点策略点数使力量或重量+2%",
    researchTitle: "棋子研究", researchDescription: "研究顺序：基础研究 → 全体尺寸 → 进阶研究。",
    allocated: "策略点数", pointsHeld: "研究点数", remaining: "剩余", current: "当前效果", next: "下级效果",
    level: "等级", cost: "消耗", maximum: "已达最高等级。", budgetSpent: "已分配全部10点策略点数，请从其他项目扣减点数。",
    minimum: "无法继续减少。", insufficientPoints: "研究点数不足。",
    advancedLocked: "购买全体尺寸研究后解锁进阶研究。",
    kingBasicLocked: "将兵和马的基础力量与重量均研究至3级。",
    queenBasicLocked: "将车和象的基础力量与重量均研究至3级。",
    kingAdvancedLocked: "将兵和马的进阶力量与重量均研究至3级。",
    queenAdvancedLocked: "将车和象的进阶力量与重量均研究至3级。",
    sizeLocked: "将全部6种棋子的基础力量与重量均研究至3级。",
    sizeDescription: "己方全体棋子尺寸+5% · 解锁进阶研究", size: "全体尺寸",
    increase: "增加", decrease: "减少", buy: "研究", preview: "3D预览", previewHint: "左右拖动旋转",
    resetView: "重置视角", previewUnavailable: "3D预览不可用，仍可继续强化和分配。",
    previewLoading: "3D预览加载中...", researchNoDecrease: "无法单独减少研究等级，请使用全部重置。",
    allocationSaved: "策略点数分配已保存。", allocationReset: "策略点数分配已重置。",
    storageUnavailable: "策略点数分配已应用，但未能保存至浏览器。",
    purchaseSuccess: "研究已完成。", purchaseFailed: "购买研究失败。", researchReset: "已重置全部研究并全额返还研究点数。",
    resetAllocation: "重置策略点数分配", resetResearch: "重置全部研究", findMatch: "寻找策略对局",
    confirm: "确认", cancel: "取消", resetQuestion: "重置所有研究？返还研究点数：",
    unspentQuestion: "尚有未分配策略点数，确定以此卡组匹配？剩余策略点数：",
    actionFailed: "请求失败，请稍后重试。", basic: "基础研究", advanced: "进阶研究", locked: "未解锁",
    force: "力量", weight: "重量", pieceList: "选择棋子",
  },
  de: {
    strategyTitle: "Strategie-Deck", strategyDescription: "Insgesamt 10 Strategie-Punkte · Max. 4 pro Wert · +2 % Kraft oder Gewicht pro Punkt",
    researchTitle: "Figurenforschung", researchDescription: "Reihenfolge: Grundlagenforschung → Gesamtgröße → Fortgeschrittene Forschung.",
    allocated: "Strategie-Punkte", pointsHeld: "Forschungspunkte", remaining: "Verbleibend", current: "Aktueller Effekt", next: "Nächster Effekt",
    level: "Stufe", cost: "Kosten", maximum: "Maximalstufe erreicht.", budgetSpent: "Alle 10 Strategie-Punkte zugewiesen. Punkte woanders abziehen.",
    minimum: "Kann nicht weiter reduziert werden.", insufficientPoints: "Nicht genügend Forschungspunkte.",
    advancedLocked: "Gesamtgröße erforschen, um Fortgeschritten freizuschalten.",
    kingBasicLocked: "Bauer & Springer Grundkraft/-gewicht auf Stufe 3 erforschen.",
    queenBasicLocked: "Turm & Läufer Grundkraft/-gewicht auf Stufe 3 erforschen.",
    kingAdvancedLocked: "Bauer & Springer Fortgeschritten auf Stufe 3 erforschen.",
    queenAdvancedLocked: "Turm & Läufer Fortgeschritten auf Stufe 3 erforschen.",
    sizeLocked: "Grundkraft/-gewicht aller 6 Figuren auf Stufe 3 erforschen.",
    sizeDescription: "Alle eigenen Figuren +5% Größe · Schaltet Fortgeschritten frei", size: "Gesamtgröße",
    increase: "Erhöhen", decrease: "Verringern", buy: "Erforschen", preview: "3D-Vorschau", previewHint: "Ziehen zum Drehen",
    resetView: "Ansicht zurücksetzen", previewUnavailable: "3D-Vorschau nicht verfügbar. Upgrades weiterhin möglich.",
    previewLoading: "3D-Vorschau lädt...", researchNoDecrease: "Einzelne Stufen können nicht verringert werden.",
    allocationSaved: "Strategie-Punkte-Zuweisung gespeichert.", allocationReset: "Strategie-Punkte-Zuweisung zurückgesetzt.",
    storageUnavailable: "Strategie-Punkte-Zuweisung angewendet, aber nicht im Browser gespeichert.",
    purchaseSuccess: "Forschung abgeschlossen.", purchaseFailed: "Forschungskauf fehlgeschlagen.", researchReset: "Forschung zurückgesetzt & Forschungspunkte erstattet.",
    resetAllocation: "Strategie-Punkte-Zuweisung zurücksetzen", resetResearch: "Forschung zurücksetzen", findMatch: "Strategie-Match suchen",
    confirm: "Bestätigen", cancel: "Abbrechen", resetQuestion: "Alle Forschungen zurücksetzen? Rückerstattung in Forschungspunkten:",
    unspentQuestion: "Nicht zugewiesene Strategie-Punkte vorhanden. Match trotzdem suchen? Restliche Strategie-Punkte:",
    actionFailed: "Anfrage fehlgeschlagen. Bitte später erneut versuchen.", basic: "Grundlagenforschung", advanced: "Fortgeschrittene Forschung", locked: "Gesperrt",
    force: "Kraft", weight: "Gewicht", pieceList: "Figur wählen",
  },
  fr: {
    strategyTitle: "Deck de stratégie", strategyDescription: "Total de 10 points de stratégie · Max 4 par stat · +2 % de Force ou de Poids par point",
    researchTitle: "Recherche des pièces", researchDescription: "Recherchez dans l'ordre : Recherche de base → Taille globale → Recherche avancée.",
    allocated: "Points de stratégie", pointsHeld: "Points de recherche", remaining: "Restant", current: "Effet actuel", next: "Effet suivant",
    level: "Niveau", cost: "Coût", maximum: "Niveau maximum atteint.", budgetSpent: "10 points de stratégie alloués. Déduisez des points ailleurs.",
    minimum: "Impossible de réduire davantage.", insufficientPoints: "Points de recherche insuffisants.",
    advancedLocked: "Achetez Taille globale pour débloquer Recherche avancée.",
    kingBasicLocked: "Recherchez Force/Poids de base pour Pion & Cavalier au Niv.3.",
    queenBasicLocked: "Recherchez Force/Poids de base pour Tour & Fou au Niv.3.",
    kingAdvancedLocked: "Recherchez Force/Poids avancé pour Pion & Cavalier au Niv.3.",
    queenAdvancedLocked: "Recherchez Force/Poids avancé pour Tour & Fou au Niv.3.",
    sizeLocked: "Recherchez Force/Poids de base pour les 6 pièces au Niv.3.",
    sizeDescription: "Taille de toutes vos pièces +5% · Débloque Recherche avancée", size: "Taille globale",
    increase: "Augmenter", decrease: "Diminuer", buy: "Rechercher", preview: "Aperçu 3D", previewHint: "Glisser pour faire pivoter",
    resetView: "Réinitialiser la vue", previewUnavailable: "Aperçu 3D indisponible. Améliorations toujours possibles.",
    previewLoading: "Chargement de l'aperçu 3D...", researchNoDecrease: "Impossible de réduire individuellement. Utilisez Réinitialisation totale.",
    allocationSaved: "Allocation des points de stratégie enregistrée.", allocationReset: "Allocation des points de stratégie réinitialisée.",
    storageUnavailable: "Allocation des points de stratégie appliquée mais non enregistrée dans le navigateur.",
    purchaseSuccess: "Recherche terminée.", purchaseFailed: "Échec de l'achat.", researchReset: "Recherche réinitialisée et points de recherche remboursés.",
    resetAllocation: "Réinitialiser l'allocation des points de stratégie", resetResearch: "Tout réinitialiser", findMatch: "Trouver partie stratégie",
    confirm: "Confirmer", cancel: "Annuler", resetQuestion: "Réinitialiser toutes les recherches ? Points de recherche remboursés :",
    unspentQuestion: "Points de stratégie non alloués restants. Lancer la partie ? Reste :",
    actionFailed: "Échec de la demande. Veuillez réessayer.", basic: "Recherche de base", advanced: "Recherche avancée", locked: "Verrouillé",
    force: "Force", weight: "Poids", pieceList: "Choisir la pièce",
  },
  es: {
    strategyTitle: "Baraja de estrategia", strategyDescription: "Total de 10 puntos de estrategia · Máx 4 por atributo · +2% de Fuerza o Peso por punto",
    researchTitle: "Investigación de piezas", researchDescription: "Investiga en orden: Investigación básica → Tamaño global → Investigación avanzada.",
    allocated: "Puntos de estrategia", pointsHeld: "Puntos de investigación", remaining: "Restante", current: "Efecto actual", next: "Siguiente efecto",
    level: "Nivel", cost: "Coste", maximum: "Nivel máximo alcanzado.", budgetSpent: "10 puntos de estrategia asignados. Resta puntos de otro atributo.",
    minimum: "No se puede reducir más.", insufficientPoints: "Puntos de investigación insuficientes.",
    advancedLocked: "Investiga Tamaño global para desbloquear Avanzada.",
    kingBasicLocked: "Investiga Fuerza/Peso básico de Peón y Caballo a Nvl.3.",
    queenBasicLocked: "Investiga Fuerza/Peso básico de Torre y Alfil a Nvl.3.",
    kingAdvancedLocked: "Investiga Fuerza/Peso avanzado de Peón y Caballo a Nvl.3.",
    queenAdvancedLocked: "Investiga Fuerza/Peso avanzado de Torre y Alfil a Nvl.3.",
    sizeLocked: "Investiga Fuerza/Peso básico de las 6 piezas a Nvl.3.",
    sizeDescription: "Tamaño de todas tus piezas +5% · Desbloquea Avanzada", size: "Tamaño global",
    increase: "Aumentar", decrease: "Disminuir", buy: "Investigar", preview: "Vista 3D", previewHint: "Arrastra para rotar",
    resetView: "Restablecer vista", previewUnavailable: "Vista 3D no disponible. Aún puedes mejorar y asignar.",
    previewLoading: "Cargando vista 3D...", researchNoDecrease: "No se puede reducir individualmente. Usa Reinicio total.",
    allocationSaved: "Asignación de puntos de estrategia guardada.", allocationReset: "Asignación de puntos de estrategia restablecida.",
    storageUnavailable: "Asignación de puntos de estrategia aplicada pero no guardada en el navegador.",
    purchaseSuccess: "Investigación completada.", purchaseFailed: "Error al comprar investigación.", researchReset: "Investigación restablecida y puntos de investigación reembolsados.",
    resetAllocation: "Restablecer asignación de puntos de estrategia", resetResearch: "Restablecer toda la investigación", findMatch: "Buscar partida de estrategia",
    confirm: "Confirmar", cancel: "Cancelar", resetQuestion: "¿Restablecer todas las investigaciones? Puntos de investigación reembolsados:",
    unspentQuestion: "Tienes puntos de estrategia sin asignar. ¿Buscar partida? Restante:",
    actionFailed: "Error en la solicitud. Inténtalo de nuevo.", basic: "Investigación básica", advanced: "Investigación avanzada", locked: "Bloqueado",
    force: "Fuerza", weight: "Peso", pieceList: "Seleccionar pieza",
  },
  ru: {
    strategyTitle: "Стратегическая колода", strategyDescription: "Всего 10 стратегических очков · Макс. 4 на стат · +2% Силы или Веса за очко",
    researchTitle: "Исследования фигур", researchDescription: "Изучайте по порядку: Базовые исследования → Общий размер → Продвинутые исследования.",
    allocated: "Стратегические очки", pointsHeld: "Очки исследований", remaining: "Осталось", current: "Текущий эффект", next: "След. эффект",
    level: "Уровень", cost: "Цена", maximum: "Максимальный уровень.", budgetSpent: "Все 10 стратегических очков распределены. Уменьшите другой стат.",
    minimum: "Нельзя уменьшить больше.", insufficientPoints: "Недостаточно очков исследований.",
    advancedLocked: "Изучите Общий размер, чтобы открыть Продвинутые.",
    kingBasicLocked: "Изучите базовые Силу и Вес Пешки и Коня до 3 ур.",
    queenBasicLocked: "Изучите базовые Силу и Вес Ладьи и Слона до 3 ур.",
    kingAdvancedLocked: "Изучите продвинутые Силу и Вес Пешки и Коня до 3 ур.",
    queenAdvancedLocked: "Изучите продвинутые Силу и Вес Ладьи и Слона до 3 ур.",
    sizeLocked: "Изучите базовые Силу и Вес всех 6 фигур до 3 ур.",
    sizeDescription: "Размер всех своих фигур +5% · Открывает Продвинутые", size: "Общий размер",
    increase: "Увеличить", decrease: "Уменьшить", buy: "Изучить", preview: "3D-просмотр", previewHint: "Тяните для вращения",
    resetView: "Сбросить вид", previewUnavailable: "3D-просмотр недоступен. Улучшения по-прежнему работают.",
    previewLoading: "Загрузка 3D...", researchNoDecrease: "Нельзя сбрасывать по отдельности. Используйте Полный сброс.",
    allocationSaved: "Распределение стратегических очков сохранено.", allocationReset: "Распределение стратегических очков сброшено.",
    storageUnavailable: "Распределение стратегических очков применено, но не сохранено в браузере.",
    purchaseSuccess: "Исследование завершено.", purchaseFailed: "Не удалось купить исследование.", researchReset: "Исследования сброшены, очки исследований возвращены.",
    resetAllocation: "Сбросить распределение стратегических очков", resetResearch: "Сбросить исследования", findMatch: "Найти матч (стратегия)",
    confirm: "Подтвердить", cancel: "Отмена", resetQuestion: "Сбросить все исследования? Возврат очков исследований:",
    unspentQuestion: "Остались нераспределенные стратегические очки. Искать матч? Осталось стратегических очков:",
    actionFailed: "Ошибка запроса. Повторите попытку позже.", basic: "Базовые исследования", advanced: "Продвинутые исследования", locked: "Закрыто",
    force: "Сила", weight: "Вес", pieceList: "Выбор фигуры",
  },
  "pt-BR": {
    strategyTitle: "Deck de Estratégia", strategyDescription: "Total de 10 pontos de estratégia · Máx 4 por atributo · +2% de Força ou Peso por ponto",
    researchTitle: "Pesquisa de Peças", researchDescription: "Pesquise na ordem: Pesquisa Básica → Tamanho Geral → Pesquisa Avançada.",
    allocated: "Pontos de estratégia", pointsHeld: "Pontos de pesquisa", remaining: "Restante", current: "Efeito Atual", next: "Próximo Efeito",
    level: "Nível", cost: "Custo", maximum: "Nível máximo atingido.", budgetSpent: "Todos os 10 pontos de estratégia distribuídos. Reduza de outro atributo.",
    minimum: "Não é possível reduzir mais.", insufficientPoints: "Pontos de pesquisa insuficientes.",
    advancedLocked: "Compre Tamanho Geral para desbloquear Pesquisa Avançada.",
    kingBasicLocked: "Pesquise Força e Peso Básicos do Peão e Cavalo até Nv.3.",
    queenBasicLocked: "Pesquise Força e Peso Básicos da Torre e Bispo até Nv.3.",
    kingAdvancedLocked: "Pesquise Força e Peso Avançados do Peão e Cavalo até Nv.3.",
    queenAdvancedLocked: "Pesquise Força e Peso Avançados da Torre e Bispo até Nv.3.",
    sizeLocked: "Pesquise Força e Peso Básicos de todas as 6 peças até Nv.3.",
    sizeDescription: "Tamanho de todas as suas peças +5% · Desbloqueia Avançado", size: "Tamanho Geral",
    increase: "Aumentar", decrease: "Diminuir", buy: "Pesquisar", preview: "Pré-visualização 3D", previewHint: "Arraste para girar",
    resetView: "Redefinir Vista", previewUnavailable: "Visualização 3D indisponível. Melhorias ainda funcionam.",
    previewLoading: "Carregando 3D...", researchNoDecrease: "Não é possível reduzir individualmente. Use Redefinição Total.",
    allocationSaved: "Distribuição de pontos de estratégia salva.", allocationReset: "Distribuição de pontos de estratégia redefinida.",
    storageUnavailable: "Distribuição de pontos de estratégia aplicada, mas não salva no navegador.",
    purchaseSuccess: "Pesquisa concluída.", purchaseFailed: "Falha ao comprar pesquisa.", researchReset: "Pesquisa redefinida e pontos de pesquisa reembolsados.",
    resetAllocation: "Redefinir distribuição de pontos de estratégia", resetResearch: "Redefinir Toda a Pesquisa", findMatch: "Buscar Partida Estratégica",
    confirm: "Confirmar", cancel: "Cancelar", resetQuestion: "Redefinir todas as pesquisas? Pontos de pesquisa reembolsados:",
    unspentQuestion: "Há pontos de estratégia não distribuídos. Buscar partida? Restante:",
    actionFailed: "Falha na solicitação. Tente novamente.", basic: "Pesquisa Básica", advanced: "Pesquisa Avançada", locked: "Bloqueado",
    force: "Força", weight: "Peso", pieceList: "Selecionar Peça",
  },
};

const existing: Record<string, string> = {
  force: "lobby.stat_force", weight: "lobby.stat_weight", basic: "lobby.upgrade_basic", advanced: "lobby.upgrade_advanced",
  findMatch: "online.find_strategy", resetResearch: "lobby.upgrade_reset_btn", cancel: "common.cancel",
  confirm: "common.confirm",
};

export function statText(key: string): string {
  const translationKey = existing[key];
  if (translationKey) {
    const translated = I18nManager.t(translationKey);
    if (translated !== translationKey) return translated;
  }
  const lang = I18nManager.getLanguage();
  const dict = TEXTS[lang] || TEXTS.ko;
  return dict[key] ?? TEXTS.ko[key] ?? key;
}

export function pieceLabel(type: PieceType): string {
  return I18nManager.t(`lobby.piece_${type.toLowerCase()}`);
}

export function effectLabel(value: number): string {
  return `+${Math.round(value * 100)}%`;
}
