import { I18nManager, type LanguageCode } from './i18n';

// Shared quest/challenge presentation copy; no storage or gameplay dependencies.
const KEYS = ["ranked","winExclusions","todayQuests","achievedTargets","unrecordedPieces","needPieces","needPuzzles","needGoldPuzzles","targetComplete","resetsSoon","practiceStart","practiceResume","practiceStage","accountResume","accountTakeover","takeoverNotice","modalRecoveryHold","livePracticeContinue","retry","retrying","details","endsSoon","account","playing","choosing","finished","allCleared","hudScore"] as const;
const ROWS: Record<LanguageCode, readonly string[]> = {
  "en": [
    "Online Ranked",
    "Excludes friendly and same-device matches",
    "Today's quests",
    "Recorded targets",
    "Not yet recorded",
    "Launch {count} more types",
    "Clear {count} more distinct puzzles",
    "Earn gold on {count} more distinct puzzles",
    "Target complete",
    "Resets soon",
    "Start personal practice",
    "Resume personal practice",
    "Saved practice: stage {stage}",
    "Resume challenge",
    "Continue on this device",
    "Continuing transfers this attempt from the other device.",
    "This account attempt cannot resume after a mid-stage interruption. End it or start separate personal practice. Its progress will not carry over.",
    "Continue this run as personal practice",
    "Reconnect",
    "Checking connection…",
    "Cards and detailed rules",
    "Ends soon",
    "Account",
    "{stage}/10 in progress",
    "{completed} cleared · Choose a card",
    "Attempt ended · {completed}/10 cleared",
    "10/10 cleared",
    "Cleared {completed} · {turns} turns in cleared stages"
  ],
  "ko": [
    "온라인 랭크",
    "친선전·같은 기기 2인 대전 제외",
    "오늘의 퀘스트",
    "달성 대상",
    "아직 기록되지 않은 기물",
    "추가 {count}종 발사",
    "다른 퍼즐 {count}개 더 완료",
    "다른 퍼즐 {count}개 더 금메달",
    "목표 완료",
    "곧 초기화",
    "개인 연습 시작",
    "개인 연습 이어하기",
    "저장된 연습: {stage}단계",
    "도전 이어하기",
    "이 기기에서 이어하기",
    "이어하면 다른 기기에서는 이 도전을 계속할 수 없습니다.",
    "스테이지 도중 중단되어 계정 도전을 이어갈 수 없습니다. 종료하거나 별도의 개인 연습을 시작하세요. 이 도전의 진행 상황은 개인 연습으로 이어지지 않습니다.",
    "현재 진행을 개인 연습으로 계속",
    "다시 연결",
    "연결 확인 중…",
    "카드 구성과 자세한 규칙",
    "곧 종료",
    "계정",
    "{stage}/10 진행 중",
    "{completed}단계 완료 · 카드 선택",
    "도전 종료 · {completed}/10 완료",
    "10/10 완료",
    "완료 {completed}개 · 완료 구간 {turns}턴"
  ],
  "ja": [
    "オンラインランク",
    "フレンド戦・同じ端末の対戦は対象外",
    "今日のクエスト",
    "達成対象",
    "まだ記録されていない駒",
    "あと{count}種類を発射",
    "異なるパズルをあと{count}個クリア",
    "異なるパズルあと{count}個でゴールド",
    "目標達成",
    "まもなくリセット",
    "個人練習を開始",
    "個人練習を再開",
    "保存済み練習：ステージ{stage}",
    "挑戦を再開",
    "この端末で再開",
    "再開すると他の端末ではこの挑戦を続けられません。",
    "ステージ途中で中断したため再開できません。終了するか別の個人練習を開始してください。この挑戦の進捗は引き継がれません。",
    "現在の進行を個人練習で続ける",
    "再接続",
    "接続を確認中…",
    "カード構成と詳細ルール",
    "まもなく終了",
    "アカウント",
    "{stage}/10 進行中",
    "{completed}クリア・カード選択",
    "挑戦終了・{completed}/10クリア",
    "10/10クリア",
    "クリア{completed}・クリア区間{turns}ターン"
  ],
  "zh-CN": [
    "在线排位",
    "不含好友对战和同设备双人对战",
    "今日任务",
    "已记录目标",
    "尚未记录的棋子",
    "再发射{count}种棋子",
    "再完成{count}个不同谜题",
    "再在{count}个不同谜题获得金牌",
    "目标完成",
    "即将重置",
    "开始个人练习",
    "继续个人练习",
    "已保存练习：第{stage}关",
    "继续挑战",
    "在此设备继续",
    "继续后将无法在其他设备继续此挑战。",
    "关卡中途已中断，无法继续账户挑战。请结束或开始独立个人练习。此挑战进度不会转入练习。",
    "以个人练习继续当前进度",
    "重新连接",
    "正在检查连接…",
    "卡牌配置与详细规则",
    "即将结束",
    "账户",
    "{stage}/10 进行中",
    "完成{completed}关 · 选择卡牌",
    "挑战结束 · 完成{completed}/10",
    "完成10/10",
    "完成{completed}关 · 已完成关卡{turns}回合"
  ],
  "de": [
    "Online-Rangliste",
    "Freundschafts- und lokale Duelle zählen nicht",
    "Heutige Aufgaben",
    "Erfasste Ziele",
    "Noch nicht erfasste Figuren",
    "Noch {count} Figurenarten starten",
    "Noch {count} verschiedene Rätsel lösen",
    "Gold in {count} weiteren verschiedenen Rätseln",
    "Ziel erreicht",
    "Wird bald zurückgesetzt",
    "Persönliches Training starten",
    "Persönliches Training fortsetzen",
    "Gespeichertes Training: Stufe {stage}",
    "Versuch fortsetzen",
    "Auf diesem Gerät fortsetzen",
    "Danach kann dieser Versuch nicht auf dem anderen Gerät fortgesetzt werden.",
    "Nach einer Unterbrechung innerhalb einer Stufe ist keine Kontofortsetzung möglich. Beende den Versuch oder starte separates Training. Der Fortschritt wird nicht übertragen.",
    "Diesen Lauf als Training fortsetzen",
    "Neu verbinden",
    "Verbindung wird geprüft…",
    "Karten und genaue Regeln",
    "Endet bald",
    "Konto",
    "{stage}/10 läuft",
    "{completed} geschafft · Karte wählen",
    "Versuch beendet · {completed}/10",
    "10/10 geschafft",
    "{completed} geschafft · {turns} Züge in abgeschlossenen Stufen"
  ],
  "fr": [
    "Classé en ligne",
    "Hors matchs amicaux et sur le même appareil",
    "Quêtes du jour",
    "Objectifs enregistrés",
    "Pièces pas encore enregistrées",
    "Lancer encore {count} types",
    "Terminer encore {count} puzzles distincts",
    "Or sur encore {count} puzzles distincts",
    "Objectif atteint",
    "Réinitialisation imminente",
    "Commencer un entraînement personnel",
    "Reprendre l'entraînement personnel",
    "Entraînement sauvegardé : niveau {stage}",
    "Reprendre le défi",
    "Continuer sur cet appareil",
    "Ce défi ne pourra plus continuer sur l'autre appareil.",
    "Ce défi ne peut pas reprendre après une interruption en cours de niveau. Terminez-le ou démarrez un entraînement séparé. La progression ne sera pas transférée.",
    "Continuer cette partie en entraînement",
    "Reconnecter",
    "Vérification de connexion…",
    "Cartes et règles détaillées",
    "Fin imminente",
    "Compte",
    "{stage}/10 en cours",
    "{completed} terminés · Choisir une carte",
    "Défi terminé · {completed}/10",
    "10/10 terminés",
    "{completed} terminés · {turns} tours dans les niveaux terminés"
  ],
  "es": [
    "Clasificatoria en línea",
    "No incluye amistosas ni partidas locales",
    "Misiones de hoy",
    "Objetivos registrados",
    "Piezas aún no registradas",
    "Lanza {count} tipos más",
    "Completa {count} puzles distintos más",
    "Oro en {count} puzles distintos más",
    "Objetivo completado",
    "Reinicio próximo",
    "Iniciar práctica personal",
    "Continuar práctica personal",
    "Práctica guardada: etapa {stage}",
    "Continuar desafío",
    "Continuar en este dispositivo",
    "No podrás continuar este intento en el otro dispositivo.",
    "No se puede retomar tras interrumpir una etapa. Termina el intento o inicia una práctica independiente. El progreso no se transferirá.",
    "Continuar esta partida como práctica",
    "Reconectar",
    "Comprobando conexión…",
    "Cartas y reglas detalladas",
    "Termina pronto",
    "Cuenta",
    "{stage}/10 en curso",
    "{completed} completadas · Elige carta",
    "Intento terminado · {completed}/10",
    "10/10 completadas",
    "{completed} completadas · {turns} turnos en etapas completadas"
  ],
  "ru": [
    "Сетевой рейтинг",
    "Без дружеских и локальных матчей",
    "Задания на сегодня",
    "Учтённые цели",
    "Ещё не учтённые фигуры",
    "Запустите ещё {count} типов",
    "Решите ещё {count} разных головоломок",
    "Золото ещё в {count} разных головоломках",
    "Цель выполнена",
    "Скоро сброс",
    "Начать личную тренировку",
    "Продолжить личную тренировку",
    "Сохранённая тренировка: этап {stage}",
    "Продолжить испытание",
    "Продолжить на этом устройстве",
    "После этого попытку нельзя продолжить на другом устройстве.",
    "После прерывания внутри этапа попытку нельзя продолжить. Завершите её или начните отдельную тренировку. Прогресс не переносится.",
    "Продолжить эту игру как тренировку",
    "Подключиться снова",
    "Проверка соединения…",
    "Карты и подробные правила",
    "Скоро завершится",
    "Аккаунт",
    "{stage}/10 в процессе",
    "Пройдено {completed} · Выбор карты",
    "Попытка завершена · {completed}/10",
    "Пройдено 10/10",
    "Пройдено {completed} · {turns} ходов на пройденных этапах"
  ],
  "pt-BR": [
    "Ranqueado online",
    "Não inclui amistosas nem partidas no mesmo aparelho",
    "Missões de hoje",
    "Alvos registrados",
    "Peças ainda não registradas",
    "Lance mais {count} tipos",
    "Conclua mais {count} puzzles distintos",
    "Ouro em mais {count} puzzles distintos",
    "Objetivo concluído",
    "Reinicia em breve",
    "Iniciar prática pessoal",
    "Continuar prática pessoal",
    "Prática salva: fase {stage}",
    "Continuar desafio",
    "Continuar neste dispositivo",
    "Depois disso, não será possível continuar esta tentativa no outro dispositivo.",
    "Não é possível retomar após interromper uma fase. Encerre a tentativa ou inicie uma prática separada. O progresso não será transferido.",
    "Continuar esta partida como prática",
    "Reconectar",
    "Verificando conexão…",
    "Cartas e regras detalhadas",
    "Termina em breve",
    "Conta",
    "{stage}/10 em andamento",
    "{completed} concluídas · Escolha uma carta",
    "Tentativa encerrada · {completed}/10",
    "10/10 concluídas",
    "{completed} concluídas · {turns} turnos nas fases concluídas"
  ]
};
export function progressUiCopy() {
  const row = ROWS[I18nManager.getLanguage()];
  return Object.fromEntries(KEYS.map((key, index) => [key, row[index]])) as Record<typeof KEYS[number], string>;
}
