import { I18nManager, type LanguageCode } from "./i18n";

/** 퍼즐 화면에서만 사용하는 문구 모음입니다. 모든 UI 문구는 9개 언어에 대응합니다. */
const PUZZLE_TEXTS: Record<LanguageCode, Record<string, string>> = {
  ko: {
    library_title: "퍼즐 도전",
    library_desc: "짧은 조건을 달성하며 알까기 감각을 익혀 보세요.",
    chapter: "챕터 {chapter}",
    chapter_1: "기초 타격",
    chapter_2: "각도와 연쇄",
    chapter_3: "고급 상황",
    locked: "선행 챕터 3문제 클리어 필요",
    cleared: "클리어",
    available: "도전 가능",
    medal: "메달",
    no_medal: "미획득",
    medal_bronze: "동메달",
    medal_silver: "은메달",
    medal_gold: "금메달",
    detail: "문제 상세",
    board_preview: "배치 미리보기",
    objective: "목표",
    gold_condition: "금메달 조건",
    restrictions: "능력 제한",
    hint: "힌트",
    hint_level: "힌트 {level}단계",
    start: "문제 시작",
    back: "목록으로",
    close: "퍼즐 종료",
    selected: "선택됨",
    shots_remaining: "남은 발사 {count}회",
    target: "문제 목표",
    protected: "보호 대상",
    restart: "다시 시작",
    show_hint: "힌트 보기",
    hide_hint: "힌트 닫기",
    result_clear: "문제 클리어!",
    result_fail: "조건을 달성하지 못했습니다",
    result_medal: "획득 메달: {medal}",
    result_objective: "목표 조건",
    result_gold: "금메달 조건",
    condition_met: "달성",
    condition_unmet: "미달성",
    retry: "다시 도전",
    next: "다음 문제",
    ability_policy: "연구·전략 덱·런 카드가 적용되지 않으며, 승급과 킹 특수 능력을 사용할 수 없습니다.",
    special_king: "킹 특수 능력은 사용할 수 없지만 타점은 자유롭게 설정할 수 있습니다.",
    special_promotion: "이번 12문제에는 새 승급이 없으며 승급을 사용할 수 없습니다.",
    default_title: "퍼즐 {index}",
    default_objective: "정해진 조건을 만족해 상대 말을 판 밖으로 보내세요.",
    default_gold: "남은 발사를 보존하고 목표를 달성하세요.",
    default_limit: "사용 가능한 발사 횟수를 확인하세요.",
    default_hint_1: "보호 대상과 목표 말의 위치를 먼저 살펴보세요.",
    default_hint_2: "반사각과 충돌 순서를 함께 계산해 보세요.",
  },
  en: {
    library_title: "Puzzle Challenges",
    library_desc: "Practice your alkkagi skills by clearing short, focused objectives.",
    chapter: "Chapter {chapter}",
    chapter_1: "Basic Strikes",
    chapter_2: "Angles and Chains",
    chapter_3: "Advanced Situations",
    locked: "Clear 3 puzzles in the previous chapter",
    cleared: "Cleared",
    available: "Available",
    medal: "Medal",
    no_medal: "None",
    medal_bronze: "Bronze",
    medal_silver: "Silver",
    medal_gold: "Gold",
    detail: "Puzzle Details",
    board_preview: "Board preview",
    objective: "Objective",
    gold_condition: "Gold condition",
    restrictions: "Ability limits",
    hint: "Hint",
    hint_level: "Hint {level}",
    start: "Start puzzle",
    back: "Back to list",
    close: "Exit puzzles",
    selected: "Selected",
    shots_remaining: "{count} shots remaining",
    target: "Puzzle target",
    protected: "Protected piece",
    restart: "Restart",
    show_hint: "Show hint",
    hide_hint: "Hide hint",
    result_clear: "Puzzle cleared!",
    result_fail: "The conditions were not met",
    result_medal: "Medal earned: {medal}",
    result_objective: "Objective",
    result_gold: "Gold condition",
    condition_met: "Met",
    condition_unmet: "Not met",
    retry: "Try again",
    next: "Next puzzle",
    ability_policy: "Research, strategy decks, and run cards are disabled. Promotion and the king special ability cannot be used.",
    special_king: "The king special ability is disabled, but its strike point can be set freely.",
    special_promotion: "These 12 puzzles add no new promotion, and promotion cannot be used.",
    default_title: "Puzzle {index}",
    default_objective: "Send the opposing pieces off the board while meeting the stated conditions.",
    default_gold: "Preserve your remaining shots while meeting the objective.",
    default_limit: "Check the number of shots available.",
    default_hint_1: "Study the protected piece and the target positions first.",
    default_hint_2: "Plan the reflection angle and collision order together.",
  },
  ja: {
    library_title: "パズル挑戦",
    library_desc: "短い目標を達成してアルカッキの感覚を磨きましょう。",
    chapter: "チャプター {chapter}",
    chapter_1: "基本の打撃",
    chapter_2: "角度と連鎖",
    chapter_3: "上級状況",
    locked: "前のチャプターを3問クリアすると解放",
    cleared: "クリア",
    available: "挑戦可能",
    medal: "メダル",
    no_medal: "未獲得",
    medal_bronze: "銅メダル",
    medal_silver: "銀メダル",
    medal_gold: "金メダル",
    detail: "問題の詳細",
    board_preview: "配置プレビュー",
    objective: "目標",
    gold_condition: "金メダル条件",
    restrictions: "能力制限",
    hint: "ヒント",
    hint_level: "ヒント {level}段階",
    start: "問題を開始",
    back: "一覧へ戻る",
    close: "パズルを終了",
    selected: "選択中",
    shots_remaining: "残り{count}発",
    target: "問題の目標",
    protected: "保護対象",
    restart: "リスタート",
    show_hint: "ヒントを見る",
    hide_hint: "ヒントを閉じる",
    result_clear: "問題クリア！",
    result_fail: "条件を達成できませんでした",
    result_medal: "獲得メダル: {medal}",
    result_objective: "目標条件",
    result_gold: "金メダル条件",
    condition_met: "達成",
    condition_unmet: "未達成",
    retry: "もう一度挑戦",
    next: "次の問題",
    ability_policy: "研究・戦略デッキ・ランカードは適用されず、昇格とキングの特殊能力は使えません。",
    special_king: "キングの特殊能力は使えませんが、打点は自由に設定できます。",
    special_promotion: "この12問に新しい昇格はなく、昇格は使用できません。",
    default_title: "パズル {index}",
    default_objective: "条件を満たしながら相手の駒を盤外へ落としましょう。",
    default_gold: "残りの発射回数を守って目標を達成しましょう。",
    default_limit: "使える発射回数を確認してください。",
    default_hint_1: "保護対象と目標の位置を先に確認しましょう。",
    default_hint_2: "反射角度と衝突順を一緒に考えましょう。",
  },
  "zh-CN": {
    library_title: "谜题挑战",
    library_desc: "完成短小目标，练习你的弹珠棋手感。",
    chapter: "章节 {chapter}",
    chapter_1: "基础击打",
    chapter_2: "角度与连锁",
    chapter_3: "高级局面",
    locked: "完成上一章3道谜题后解锁",
    cleared: "已通关",
    available: "可挑战",
    medal: "奖牌",
    no_medal: "未获得",
    medal_bronze: "铜牌",
    medal_silver: "银牌",
    medal_gold: "金牌",
    detail: "谜题详情",
    board_preview: "棋盘预览",
    objective: "目标",
    gold_condition: "金牌条件",
    restrictions: "能力限制",
    hint: "提示",
    hint_level: "提示 {level}级",
    start: "开始谜题",
    back: "返回列表",
    close: "退出谜题",
    selected: "已选择",
    shots_remaining: "剩余发射 {count}次",
    target: "谜题目标",
    protected: "保护棋子",
    restart: "重新开始",
    show_hint: "显示提示",
    hide_hint: "关闭提示",
    result_clear: "谜题通关！",
    result_fail: "未满足条件",
    result_medal: "获得奖牌：{medal}",
    result_objective: "目标条件",
    result_gold: "金牌条件",
    condition_met: "已达成",
    condition_unmet: "未达成",
    retry: "再次挑战",
    next: "下一题",
    ability_policy: "不适用研究、策略牌组和战局卡，不能使用升变和国王特殊能力。",
    special_king: "国王特殊能力不可用，但可以自由设置击打点。",
    special_promotion: "这12道谜题没有新的升变，也不能使用升变。",
    default_title: "谜题 {index}",
    default_objective: "满足指定条件，并将对方棋子弹出棋盘。",
    default_gold: "保留剩余发射次数并完成目标。",
    default_limit: "请确认可用的发射次数。",
    default_hint_1: "先观察保护棋子和目标棋子的位置。",
    default_hint_2: "同时规划反射角度和碰撞顺序。",
  },
  de: {
    library_title: "Puzzle-Herausforderungen",
    library_desc: "Übe dein Alkkagi-Gefühl mit kurzen, klaren Zielen.",
    chapter: "Kapitel {chapter}",
    chapter_1: "Grundschläge",
    chapter_2: "Winkel und Ketten",
    chapter_3: "Fortgeschrittene Situationen",
    locked: "Schließe 3 Rätsel im vorherigen Kapitel ab",
    cleared: "Abgeschlossen",
    available: "Verfügbar",
    medal: "Medaille",
    no_medal: "Keine",
    medal_bronze: "Bronze",
    medal_silver: "Silber",
    medal_gold: "Gold",
    detail: "Rätseldetails",
    board_preview: "Brettvorschau",
    objective: "Ziel",
    gold_condition: "Goldbedingung",
    restrictions: "Fähigkeitslimits",
    hint: "Hinweis",
    hint_level: "Hinweis Stufe {level}",
    start: "Rätsel starten",
    back: "Zur Liste",
    close: "Rätsel verlassen",
    selected: "Ausgewählt",
    shots_remaining: "{count} Schüsse übrig",
    target: "Rätselziel",
    protected: "Geschützte Figur",
    restart: "Neustart",
    show_hint: "Hinweis anzeigen",
    hide_hint: "Hinweis schließen",
    result_clear: "Rätsel gelöst!",
    result_fail: "Die Bedingungen wurden nicht erfüllt",
    result_medal: "Medaille: {medal}",
    result_objective: "Zielbedingung",
    result_gold: "Goldbedingung",
    condition_met: "Erfüllt",
    condition_unmet: "Nicht erfüllt",
    retry: "Erneut versuchen",
    next: "Nächstes Rätsel",
    ability_policy: "Forschung, Strategiedecks und Laufkarten sind deaktiviert. Umwandlung und die Königsfähigkeit sind nicht möglich.",
    special_king: "Die Königsfähigkeit ist deaktiviert, der Treffpunkt kann aber frei gesetzt werden.",
    special_promotion: "Diese 12 Rätsel enthalten keine neue Umwandlung; Umwandlung ist nicht möglich.",
    default_title: "Rätsel {index}",
    default_objective: "Erfülle die Bedingungen und befördere die gegnerischen Figuren vom Brett.",
    default_gold: "Erfülle das Ziel und bewahre deine übrigen Schüsse.",
    default_limit: "Prüfe die Anzahl der verfügbaren Schüsse.",
    default_hint_1: "Prüfe zuerst geschützte und zielende Figuren.",
    default_hint_2: "Plane Reflexionswinkel und Kollisionsfolge zusammen.",
  },
  fr: {
    library_title: "Défis puzzle",
    library_desc: "Entraînez votre précision avec des objectifs courts.",
    chapter: "Chapitre {chapter}",
    chapter_1: "Frappes de base",
    chapter_2: "Angles et chaînes",
    chapter_3: "Situations avancées",
    locked: "Terminez 3 puzzles du chapitre précédent",
    cleared: "Réussi",
    available: "Disponible",
    medal: "Médaille",
    no_medal: "Aucune",
    medal_bronze: "Bronze",
    medal_silver: "Argent",
    medal_gold: "Or",
    detail: "Détails du puzzle",
    board_preview: "Aperçu du plateau",
    objective: "Objectif",
    gold_condition: "Condition or",
    restrictions: "Limites de capacité",
    hint: "Indice",
    hint_level: "Indice niveau {level}",
    start: "Commencer le puzzle",
    back: "Retour à la liste",
    close: "Quitter les puzzles",
    selected: "Sélectionné",
    shots_remaining: "{count} tirs restants",
    target: "Objectif du puzzle",
    protected: "Pièce protégée",
    restart: "Recommencer",
    show_hint: "Afficher l'indice",
    hide_hint: "Masquer l'indice",
    result_clear: "Puzzle réussi !",
    result_fail: "Les conditions ne sont pas remplies",
    result_medal: "Médaille obtenue : {medal}",
    result_objective: "Condition de l'objectif",
    result_gold: "Condition or",
    condition_met: "Réussi",
    condition_unmet: "Non rempli",
    retry: "Réessayer",
    next: "Puzzle suivant",
    ability_policy: "La recherche, les decks stratégiques et les cartes de run sont désactivés. Promotion et capacité spéciale du roi sont interdites.",
    special_king: "La capacité spéciale du roi est désactivée, mais son point de frappe reste libre.",
    special_promotion: "Ces 12 puzzles n'ajoutent aucune promotion et la promotion est interdite.",
    default_title: "Puzzle {index}",
    default_objective: "Respectez les conditions et envoyez les pièces adverses hors du plateau.",
    default_gold: "Conservez vos tirs restants tout en atteignant l'objectif.",
    default_limit: "Vérifiez le nombre de tirs disponibles.",
    default_hint_1: "Observez d'abord la pièce protégée et les cibles.",
    default_hint_2: "Planifiez ensemble l'angle de rebond et l'ordre des collisions.",
  },
  es: {
    library_title: "Desafíos de rompecabezas",
    library_desc: "Practica tu precisión con objetivos breves y concretos.",
    chapter: "Capítulo {chapter}",
    chapter_1: "Golpes básicos",
    chapter_2: "Ángulos y cadenas",
    chapter_3: "Situaciones avanzadas",
    locked: "Completa 3 rompecabezas del capítulo anterior",
    cleared: "Completado",
    available: "Disponible",
    medal: "Medalla",
    no_medal: "Ninguna",
    medal_bronze: "Bronce",
    medal_silver: "Plata",
    medal_gold: "Oro",
    detail: "Detalles del rompecabezas",
    board_preview: "Vista previa del tablero",
    objective: "Objetivo",
    gold_condition: "Condición de oro",
    restrictions: "Límites de habilidad",
    hint: "Pista",
    hint_level: "Pista nivel {level}",
    start: "Iniciar rompecabezas",
    back: "Volver a la lista",
    close: "Salir de los rompecabezas",
    selected: "Seleccionado",
    shots_remaining: "Quedan {count} lanzamientos",
    target: "Objetivo del rompecabezas",
    protected: "Pieza protegida",
    restart: "Reiniciar",
    show_hint: "Mostrar pista",
    hide_hint: "Ocultar pista",
    result_clear: "¡Rompecabezas superado!",
    result_fail: "No se cumplieron las condiciones",
    result_medal: "Medalla obtenida: {medal}",
    result_objective: "Condición del objetivo",
    result_gold: "Condición de oro",
    condition_met: "Cumplida",
    condition_unmet: "Sin cumplir",
    retry: "Intentar de nuevo",
    next: "Siguiente rompecabezas",
    ability_policy: "La investigación, los mazos estratégicos y las cartas de run están desactivados. No se puede usar promoción ni la habilidad especial del rey.",
    special_king: "La habilidad especial del rey está desactivada, pero puedes fijar libremente su punto de golpe.",
    special_promotion: "Estos 12 rompecabezas no añaden promociones nuevas y la promoción no está disponible.",
    default_title: "Rompecabezas {index}",
    default_objective: "Cumple las condiciones y expulsa las piezas rivales del tablero.",
    default_gold: "Conserva tus lanzamientos restantes y cumple el objetivo.",
    default_limit: "Comprueba cuántos lanzamientos tienes disponibles.",
    default_hint_1: "Mira primero la pieza protegida y las posiciones objetivo.",
    default_hint_2: "Calcula juntos el ángulo de rebote y el orden de colisión.",
  },
  ru: {
    library_title: "Головоломки",
    library_desc: "Тренируйте чувство удара, выполняя короткие задания.",
    chapter: "Глава {chapter}",
    chapter_1: "Основные удары",
    chapter_2: "Углы и цепочки",
    chapter_3: "Продвинутые ситуации",
    locked: "Пройдите 3 головоломки предыдущей главы",
    cleared: "Пройдено",
    available: "Доступно",
    medal: "Медаль",
    no_medal: "Нет",
    medal_bronze: "Бронза",
    medal_silver: "Серебро",
    medal_gold: "Золото",
    detail: "Подробности головоломки",
    board_preview: "Предпросмотр доски",
    objective: "Цель",
    gold_condition: "Условие золота",
    restrictions: "Ограничения способностей",
    hint: "Подсказка",
    hint_level: "Подсказка, уровень {level}",
    start: "Начать головоломку",
    back: "Вернуться к списку",
    close: "Выйти из головоломок",
    selected: "Выбрано",
    shots_remaining: "Осталось ударов: {count}",
    target: "Цель головоломки",
    protected: "Защищённая фигура",
    restart: "Начать заново",
    show_hint: "Показать подсказку",
    hide_hint: "Скрыть подсказку",
    result_clear: "Головоломка пройдена!",
    result_fail: "Условия не выполнены",
    result_medal: "Получена медаль: {medal}",
    result_objective: "Условие цели",
    result_gold: "Условие золота",
    condition_met: "Выполнено",
    condition_unmet: "Не выполнено",
    retry: "Попробовать снова",
    next: "Следующая головоломка",
    ability_policy: "Исследования, стратегические колоды и карты забега отключены. Превращение и особая способность короля недоступны.",
    special_king: "Особая способность короля отключена, но точку удара можно выбрать свободно.",
    special_promotion: "В этих 12 задачах нет нового превращения, и превращение использовать нельзя.",
    default_title: "Головоломка {index}",
    default_objective: "Выполните условия и столкните фигуры соперника с доски.",
    default_gold: "Сохраните оставшиеся удары и выполните цель.",
    default_limit: "Проверьте доступное число ударов.",
    default_hint_1: "Сначала изучите защищённую фигуру и цели.",
    default_hint_2: "Рассчитайте угол отражения и порядок столкновений.",
  },
  "pt-BR": {
    library_title: "Desafios de quebra-cabeça",
    library_desc: "Pratique sua precisão com objetivos curtos e claros.",
    chapter: "Capítulo {chapter}",
    chapter_1: "Tiros básicos",
    chapter_2: "Ângulos e cadeias",
    chapter_3: "Situações avançadas",
    locked: "Conclua 3 quebra-cabeças do capítulo anterior",
    cleared: "Concluído",
    available: "Disponível",
    medal: "Medalha",
    no_medal: "Nenhuma",
    medal_bronze: "Bronze",
    medal_silver: "Prata",
    medal_gold: "Ouro",
    detail: "Detalhes do quebra-cabeça",
    board_preview: "Prévia do tabuleiro",
    objective: "Objetivo",
    gold_condition: "Condição de ouro",
    restrictions: "Limites de habilidade",
    hint: "Dica",
    hint_level: "Dica nível {level}",
    start: "Iniciar quebra-cabeça",
    back: "Voltar à lista",
    close: "Sair dos quebra-cabeças",
    selected: "Selecionado",
    shots_remaining: "{count} lançamentos restantes",
    target: "Objetivo do quebra-cabeça",
    protected: "Peça protegida",
    restart: "Reiniciar",
    show_hint: "Mostrar dica",
    hide_hint: "Fechar dica",
    result_clear: "Quebra-cabeça concluído!",
    result_fail: "As condições não foram cumpridas",
    result_medal: "Medalha obtida: {medal}",
    result_objective: "Condição do objetivo",
    result_gold: "Condição de ouro",
    condition_met: "Cumprida",
    condition_unmet: "Não cumprida",
    retry: "Tentar novamente",
    next: "Próximo quebra-cabeça",
    ability_policy: "Pesquisa, decks estratégicos e cartas de rodada estão desativados. Promoção e habilidade especial do rei não podem ser usadas.",
    special_king: "A habilidade especial do rei está desativada, mas seu ponto de ataque pode ser definido livremente.",
    special_promotion: "Estes 12 quebra-cabeças não adicionam promoção nova, e promoção não pode ser usada.",
    default_title: "Quebra-cabeça {index}",
    default_objective: "Cumpra as condições e tire as peças adversárias do tabuleiro.",
    default_gold: "Preserve os lançamentos restantes e cumpra o objetivo.",
    default_limit: "Confira quantos lançamentos estão disponíveis.",
    default_hint_1: "Observe primeiro a peça protegida e as posições-alvo.",
    default_hint_2: "Planeje juntos o ângulo de reflexão e a ordem das colisões.",
  },
};

const PUZZLE_TITLES: Record<LanguageCode, readonly string[]> = {
  ko: ["마지막 한 칸", "비껴 맞히기", "돌아오는 길", "둘을 한 번에", "가운데로", "아군 사이", "누운 창", "힘을 남겨라", "넘어가는 길", "회전의 차이", "벽을 열어라", "내 해법"],
  en: ["One Space Left", "Glancing Hit", "The Way Back", "Two at Once", "To the Center", "Between Allies", "Prone Spear", "Save Your Power", "The Way Across", "Rotation Difference", "Open the Wall", "My Solution"],
  ja: ["あと一マス", "かすめ打ち", "戻る道", "一度に二つ", "中央へ", "味方の間", "伏せた槍", "力を残せ", "渡る道", "回転の違い", "壁を開け", "私の解法"],
  "zh-CN": ["最后一格", "擦边命中", "回来的路", "一次两个", "走向中央", "盟友之间", "卧倒之矛", "保留力量", "跨越之路", "旋转差异", "打开墙壁", "我的解法"],
  de: ["Das letzte Feld", "Streifschuss", "Der Rückweg", "Zwei auf einmal", "Zur Mitte", "Zwischen Verbündeten", "Liegender Speer", "Kraft bewahren", "Der Weg hinüber", "Rotationsunterschied", "Öffne die Wand", "Meine Lösung"],
  fr: ["La dernière case", "Frappe en biais", "Le chemin du retour", "Deux d'un coup", "Vers le centre", "Entre alliés", "Lance couchée", "Garder sa force", "Le chemin d'en face", "Différence de rotation", "Ouvrir le mur", "Ma solution"],
  es: ["La última casilla", "Golpe de refilón", "El camino de vuelta", "Dos de una vez", "Hacia el centro", "Entre aliados", "Lanza tumbada", "Guarda tu fuerza", "El camino al otro lado", "Diferencia de giro", "Abre la pared", "Mi solución"],
  ru: ["Последняя клетка", "Скользящий удар", "Обратный путь", "Два за раз", "К центру", "Среди союзников", "Лежащее копьё", "Сохрани силу", "Путь через край", "Разница вращения", "Откройте стену", "Моё решение"],
  "pt-BR": ["A última casa", "Golpe de raspão", "O caminho de volta", "Dois de uma vez", "Rumo ao centro", "Entre aliados", "Lança caída", "Guarde sua força", "O caminho para o outro lado", "Diferença de rotação", "Abra a parede", "Minha solução"],
};

const PUZZLE_COPY: Record<LanguageCode, { objective: string; gold: string; limit: string; hint1: string; hint2: string }> = {
  ko: { objective: "배치된 목표 말을 조건에 맞춰 판 밖으로 보내세요.", gold: "남은 발사를 보존하고 목표를 달성하세요.", limit: "발사 횟수와 허용 능력을 확인하세요.", hint1: "첫 타격의 방향과 목표 말의 정렬을 먼저 보세요.", hint2: "충돌 순서와 반사각을 함께 계산해 보세요." },
  en: { objective: "Send the marked target pieces off the board under the stated conditions.", gold: "Preserve your remaining shots while meeting the objective.", limit: "Check your shots and allowed abilities.", hint1: "Start by checking the first strike direction and target alignment.", hint2: "Plan the collision order and reflection angle together." },
  ja: { objective: "配置された目標の駒を条件に従って盤外へ落としましょう。", gold: "残りの発射を守って目標を達成しましょう。", limit: "発射回数と使用できる能力を確認してください。", hint1: "最初の打撃方向と目標の並びを確認しましょう。", hint2: "衝突順と反射角度を一緒に考えましょう。" },
  "zh-CN": { objective: "按照指定条件，将标记的目标棋子弹出棋盘。", gold: "保留剩余发射次数并完成目标。", limit: "确认发射次数和可用能力。", hint1: "先检查第一次击打方向和目标棋子的排列。", hint2: "一起规划碰撞顺序和反射角度。" },
  de: { objective: "Befördere die markierten Zielfiguren unter den angegebenen Bedingungen vom Brett.", gold: "Bewahre deine übrigen Schüsse und erfülle das Ziel.", limit: "Prüfe Schüsse und erlaubte Fähigkeiten.", hint1: "Prüfe zuerst Richtung des ersten Schlags und Ziellinie.", hint2: "Plane Kollisionsfolge und Reflexionswinkel zusammen." },
  fr: { objective: "Envoyez les pièces cibles hors du plateau en respectant les conditions.", gold: "Conservez vos tirs restants tout en atteignant l'objectif.", limit: "Vérifiez vos tirs et les capacités autorisées.", hint1: "Commencez par la direction du premier tir et l'alignement de la cible.", hint2: "Planifiez l'ordre des collisions et l'angle de rebond." },
  es: { objective: "Expulsa las piezas objetivo marcadas del tablero cumpliendo las condiciones.", gold: "Conserva tus lanzamientos restantes y cumple el objetivo.", limit: "Comprueba tus lanzamientos y habilidades permitidas.", hint1: "Mira primero la dirección del golpe inicial y la alineación del objetivo.", hint2: "Calcula juntos el orden de colisión y el ángulo de rebote." },
  ru: { objective: "При соблюдении условий столкните отмеченные цели с доски.", gold: "Сохраните оставшиеся удары и выполните цель.", limit: "Проверьте удары и доступные способности.", hint1: "Сначала изучите направление первого удара и линию цели.", hint2: "Рассчитайте порядок столкновений и угол отражения." },
  "pt-BR": { objective: "Tire as peças-alvo marcadas do tabuleiro seguindo as condições.", gold: "Preserve os lançamentos restantes e cumpra o objetivo.", limit: "Confira seus lançamentos e habilidades permitidas.", hint1: "Observe primeiro a direção do tiro inicial e o alinhamento do alvo.", hint2: "Planeje juntos a ordem das colisões e o ângulo de reflexão." },
};

type PuzzleDetail = readonly [objective: string, gold: string, hint1: string, hint2: string];
const PUZZLE_DETAILS: Record<LanguageCode, readonly PuzzleDetail[]> = {
  ko: [
    ["2발 안에 적 폰을 장외로 보내세요.", "1발로 적 폰을 보내고 내 폰을 살리세요.", "먼저 목표 말의 진행 방향을 살펴보세요.", "약한 측면 타격으로 목표만 밀어 보세요."],
    ["2발 안에 적 비숍을 장외로 보내고 보호 폰을 지키세요.", "보호 폰과 접촉하지 않고 적 비숍을 보내세요.", "보호 말 주변의 빈 공간을 먼저 확인하세요.", "보호 말의 반대쪽에서 비껴 밀어 보세요."],
    ["2발 안에 적 폰을 고정벽 반사로 보내세요.", "2발 안에 벽 반사 후 목표를 맞히세요.", "직접 충돌보다 고정벽을 먼저 이용해 보세요.", "룩을 벽 쪽으로 보내 반사된 뒤 목표를 맞히세요."],
    ["2발 안에 적 폰 2개를 모두 보내세요.", "1발로 두 목표를 모두 보내세요.", "두 목표의 일직선과 간격을 비교해 보세요.", "첫 충돌 뒤 두 번째 목표로 이어지는 방향을 만드세요."],
    ["3발 안에 적 폰을 중앙 구멍으로 보내세요.", "1발로 중앙 구멍에 보내고 내 룩을 살리세요.", "중앙 구멍의 가장자리와 목표의 이동선을 관찰하세요.", "목표의 속도를 중앙 구멍 방향으로 바꾸세요."],
    ["3발 안에 적 룩을 보내고 보호 킹을 살리세요.", "보호 킹과 접촉하지 않고 적 룩을 보내세요.", "보호 말이 움직이지 않을 빈 각도를 찾으세요.", "적 말의 측면만 건드리도록 세기를 낮춰 보세요."],
    ["3발 안에 적 폰 2개를 모두 보내세요.", "2발 안에 두 목표를 보내고 내 비숍을 살리세요.", "누운 말도 그대로 선택해 발사할 수 있습니다.", "낮은 자세가 만드는 첫 충돌 각도를 활용하세요."],
    ["2발 안에 적 폰을 보내세요.", "중앙 타점과 60% 이하의 세기로 목표를 보내세요.", "룩의 중앙 타점은 회전을 줄여 줍니다.", "표시 세기를 60% 이하로 맞춰 목표를 밀어 보세요."],
    ["2발 안에 다중 구멍 사이의 적 폰을 나이트로 보내세요.", "1발로 목표를 보내고 내 나이트를 살리세요.", "나이트는 앞의 장애물을 뛰어넘을 수 있습니다.", "구멍을 피하는 착지 지점을 먼저 정하세요."],
    ["3발 안에 적 폰을 보내고 보호 폰과 접촉하지 마세요.", "커스텀 타점으로 2발 안에 목표를 보내고 보호 폰을 지키세요.", "기둥을 기준으로 비숍의 접근선을 바꿔 보세요.", "커스텀 타점으로 첫 회전량을 조절하세요."],
    ["4발 안에 벽을 파괴하고 적 폰을 보내세요.", "2발 안에 벽 반사 순서로 목표를 보내고 내 룩을 살리세요.", "벽의 남은 내구도를 확인하고 길을 열어야 합니다.", "첫 샷으로 벽을 파괴한 뒤 열린 경로를 이용하세요."],
    ["4발 안에 적 폰 3개를 모두 보내고 보호 킹을 살리세요.", "2발 안에 세 목표를 보내고 보호 킹을 살리세요.", "목표의 순서를 정하면 샷 수를 줄일 수 있습니다.", "보호 아군 쪽으로 튀지 않는 연쇄 각도를 찾으세요."],
  ],
  en: [
    ["Send the enemy pawn off the board in 2 shots.", "Send it in 1 shot while keeping your pawn alive.", "Study the target's direction first.", "Use a light glancing hit to push only the target."],
    ["Send the enemy bishop off in 2 shots while protecting the pawn.", "Send the bishop without touching the protected pawn.", "Check the open space around the protected piece.", "Push from the side opposite the protected piece."],
    ["Send the enemy pawn in 2 shots using a fixed wall ricochet.", "Hit the target after the wall ricochet within 2 shots.", "Use the fixed wall before attempting a direct collision.", "Send the rook to the wall, then hit the target after the bounce."],
    ["Send both enemy pawns off in 2 shots.", "Send both targets in 1 shot.", "Compare the targets' line and spacing.", "Create a path from the first collision to the second target."],
    ["Send the enemy pawn into the center hole in 3 shots.", "Send it into the hole in 1 shot while keeping your rook alive.", "Watch the hole edge and the target's travel line.", "Turn the target's speed toward the center hole."],
    ["Send the enemy rook off in 3 shots while keeping the king safe.", "Send the rook without touching the protected king.", "Find an open angle that leaves the protected piece still.", "Lower power so you touch only the side of the enemy piece."],
    ["Send both enemy pawns off in 3 shots.", "Send both in 2 shots while keeping your bishop alive.", "A prone piece can still be selected and launched.", "Use the first collision angle created by the low pose."],
    ["Send the enemy pawn off in 2 shots.", "Use a center hit and power of 60% or less.", "A rook center hit reduces rotation.", "Set the displayed power to 60% or less."],
    ["Send the enemy pawn through the multi-hole layout in 2 shots with the knight.", "Send it in 1 shot while keeping your knight alive.", "The knight can clear the obstacle ahead.", "Choose a landing point that avoids the holes first."],
    ["Send the enemy pawn off in 3 shots without touching the protected pawn.", "Use a custom hit to do it in 2 shots while keeping the pawn safe.", "Change the bishop's approach line around the pillar.", "Adjust the first rotation with a custom hit."],
    ["Break the wall and send the enemy pawn off in 4 shots.", "Use the wall sequence to do it in 2 shots while keeping your rook alive.", "Check the wall's remaining durability to open the path.", "Break the wall with the first shot, then use the open route."],
    ["Send all 3 enemy pawns off in 4 shots while keeping the king safe.", "Send all three in 2 shots while keeping the protected king alive.", "Choose the target order to reduce shots.", "Find a chain angle that does not rebound toward your ally."],
  ],
  ja: [
    ["2発以内に相手のポーンを盤外へ落としましょう。", "1発で落とし、自分のポーンを残しましょう。", "まず目標の進行方向を確認しましょう。", "弱いかすめ打ちで目標だけを押しましょう。"],
    ["2発以内に相手のビショップを落とし、保護ポーンを守りましょう。", "保護ポーンに触れずにビショップを落としましょう。", "保護駒の周りの空間を確認しましょう。", "保護駒と反対側からかすめて押しましょう。"],
    ["固定壁の反射を使い、2発以内に相手ポーンを落としましょう。", "2発以内に壁で反射して目標を当てましょう。", "直接衝突より先に固定壁を使いましょう。", "ルークを壁へ送り、反射後に目標を狙いましょう。"],
    ["2発以内に相手ポーン2枚を両方落としましょう。", "1発で両方の目標を落としましょう。", "二つの目標の直線と間隔を比べましょう。", "最初の衝突から二つ目へ続く方向を作りましょう。"],
    ["3発以内に相手ポーンを中央の穴へ落としましょう。", "1発で中央の穴へ落とし、自分のルークを残しましょう。", "中央の穴の縁と目標の移動線を観察しましょう。", "目標の速度を中央の穴へ向けましょう。"],
    ["3発以内に相手ルークを落とし、保護キングを残しましょう。", "保護キングに触れずにルークを落としましょう。", "保護駒が動かない空いた角度を探しましょう。", "相手の側面だけに触れるよう力を下げましょう。"],
    ["3発以内に相手ポーン2枚を両方落としましょう。", "2発以内に両方を落とし、自分のビショップを残しましょう。", "倒れた駒もそのまま選んで発射できます。", "低い姿勢が作る最初の衝突角を使いましょう。"],
    ["2発以内に相手ポーンを落としましょう。", "中央打点と60%以下の力で目標を落としましょう。", "ルークの中央打点は回転を減らします。", "表示の力を60%以下に合わせましょう。"],
    ["ナイトで複数の穴を越え、2発以内に相手ポーンを落としましょう。", "1発で目標を落とし、自分のナイトを残しましょう。", "ナイトは前の障害物を越えられます。", "穴を避ける着地点を先に決めましょう。"],
    ["3発以内に相手ポーンを落とし、保護ポーンに触れないでください。", "カスタム打点で2発以内に落とし、保護ポーンを守りましょう。", "柱を基準にビショップの進入線を変えましょう。", "カスタム打点で最初の回転量を調整しましょう。"],
    ["4発以内に壁を壊し、相手ポーンを落としましょう。", "壁反射の順序で2発以内に落とし、自分のルークを残しましょう。", "壁の残り耐久を確認して道を開きましょう。", "最初の一打で壁を壊し、開いた道を使いましょう。"],
    ["4発以内に相手ポーン3枚を落とし、保護キングを残しましょう。", "2発以内に三つの目標を落とし、保護キングを守りましょう。", "目標の順番を決めると発射数を減らせます。", "味方へ跳ね返らない連鎖角を探しましょう。"],
  ],
  "zh-CN": [
    ["在2次发射内将敌方兵弹出棋盘。", "用1次发射完成，并保留己方兵。", "先观察目标棋子的移动方向。", "用轻微的侧面击打，只推动目标。"],
    ["在2次发射内弹出敌方象，并保护己方兵。", "不碰保护兵的情况下弹出敌方象。", "先确认保护棋子周围的空位。", "从保护棋子相反的一侧擦边推动。"],
    ["利用固定墙反弹，在2次发射内弹出敌方兵。", "在2次发射内完成撞墙反弹并命中目标。", "先利用固定墙，不要直接碰撞。", "让车先撞墙，再利用反弹击中目标。"],
    ["在2次发射内弹出两枚敌方兵。", "用1次发射同时弹出两个目标。", "比较两个目标的直线和间距。", "让第一次碰撞后的方向接上第二个目标。"],
    ["在3次发射内将敌方兵送入中央洞。", "用1次发射送入中央洞，并保留己方车。", "观察中央洞边缘和目标的移动线。", "把目标速度转向中央洞。"],
    ["在3次发射内弹出敌方车并保护己方王。", "不碰保护王的情况下弹出敌方车。", "寻找不会让保护棋子移动的空角度。", "降低力度，只碰敌方棋子的侧面。"],
    ["在3次发射内弹出两枚敌方兵。", "在2次发射内完成并保留己方象。", "卧倒的棋子仍然可以选择并发射。", "利用低姿态形成的第一次碰撞角度。"],
    ["在2次发射内弹出敌方兵。", "使用中央击打点和不超过60%的力度。", "车的中央击打点可以减少旋转。", "把显示力度调到60%以下。"],
    ["用马穿过多洞布局，在2次发射内弹出敌方兵。", "用1次发射完成并保留己方马。", "马可以越过前方障碍。", "先确定避开洞口的落点。"],
    ["在3次发射内弹出敌方兵，且不能碰保护兵。", "使用自定义击打点，在2次发射内完成并保护己方兵。", "以柱子为参照改变象的接近路线。", "用自定义击打点调整第一次旋转。"],
    ["在4次发射内破坏墙壁并弹出敌方兵。", "按墙壁反弹顺序在2次发射内完成并保留己方车。", "确认墙壁剩余耐久，先打开通路。", "第一次发射破墙，再利用打开的路线。"],
    ["在4次发射内弹出3枚敌方兵并保护己方王。", "在2次发射内弹出三个目标并保留保护王。", "先决定目标顺序可以减少发射次数。", "寻找不会反弹到己方棋子的连锁角度。"],
  ],
  de: [
    ["Befördere den gegnerischen Bauern in 2 Schüssen vom Brett.", "Schaffe es mit 1 Schuss und erhalte deinen Bauern.", "Prüfe zuerst die Bewegungsrichtung des Ziels.", "Drücke nur das Ziel mit einem leichten Streifschuss."],
    ["Schlage den gegnerischen Läufer in 2 Schüssen heraus und schütze den Bauern.", "Triff den geschützten Bauern nicht.", "Prüfe zuerst den freien Raum um die geschützte Figur.", "Drücke von der gegenüberliegenden Seite."],
    ["Schlage den gegnerischen Bauern in 2 Schüssen über die feste Bande heraus.", "Triff das Ziel nach dem Bandensprung in 2 Schüssen.", "Nutze zuerst die feste Bande statt einer direkten Kollision.", "Schicke den Turm zur Bande und triff danach das Ziel."],
    ["Schlage beide gegnerischen Bauern in 2 Schüssen heraus.", "Schaffe beide Ziele mit 1 Schuss.", "Vergleiche Linie und Abstand der Ziele.", "Verbinde die erste Kollision mit dem zweiten Ziel."],
    ["Bringe den gegnerischen Bauern in 3 Schüssen ins Mittelloch.", "Schaffe es mit 1 Schuss und erhalte deinen Turm.", "Beobachte Lochkante und Laufweg des Ziels.", "Lenke die Geschwindigkeit zum Mittelloch."],
    ["Schlage den gegnerischen Turm in 3 Schüssen heraus und schütze den König.", "Berühre den geschützten König nicht.", "Finde einen freien Winkel, der die Schutzfigur ruhig lässt.", "Senke die Kraft und berühre nur die Seite."],
    ["Schlage beide gegnerischen Bauern in 3 Schüssen heraus.", "Schaffe sie in 2 Schüssen und erhalte deinen Läufer.", "Auch eine liegende Figur kann gewählt und geschnippt werden.", "Nutze den Winkel der ersten Kollision aus der niedrigen Lage."],
    ["Schlage den gegnerischen Bauern in 2 Schüssen heraus.", "Nutze einen Mittentreffer mit höchstens 60% Kraft.", "Ein Mittentreffer des Turms verringert die Drehung.", "Stelle die angezeigte Kraft auf höchstens 60%."],
    ["Schlage den gegnerischen Bauern mit dem Springer in 2 Schüssen durch mehrere Löcher.", "Schaffe es mit 1 Schuss und erhalte deinen Springer.", "Der Springer kann das Hindernis vor sich überspringen.", "Wähle zuerst einen Landepunkt ohne Loch."],
    ["Schlage den gegnerischen Bauern in 3 Schüssen heraus, ohne den geschützten Bauern zu berühren.", "Nutze einen eigenen Treffpunkt, schaffe es in 2 Schüssen und schütze den Bauern.", "Ändere die Annäherung des Läufers um die Säule.", "Steuere die erste Drehung mit einem eigenen Treffpunkt."],
    ["Zerstöre die Wand und schlage den gegnerischen Bauern in 4 Schüssen heraus.", "Nutze die Bandensequenz in 2 Schüssen und erhalte deinen Turm.", "Prüfe die Resthaltbarkeit der Wand und öffne den Weg.", "Zerstöre die Wand mit dem ersten Schuss und nutze den Weg."],
    ["Schlage 3 gegnerische Bauern in 4 Schüssen heraus und schütze den König.", "Schaffe alle drei Ziele in 2 Schüssen und erhalte den geschützten König.", "Lege die Reihenfolge fest, um Schüsse zu sparen.", "Finde einen Kettenwinkel, der nicht zum Verbündeten zurückspringt."],
  ],
  fr: [
    ["Sortez le pion adverse du plateau en 2 tirs.", "Réussissez en 1 tir en gardant votre pion.", "Observez d'abord la direction de la cible.", "Poussez seulement la cible avec une frappe légère."],
    ["Sortez le fou adverse en 2 tirs en protégeant le pion.", "Sortez le fou sans toucher le pion protégé.", "Vérifiez l'espace libre autour de la pièce protégée.", "Poussez depuis le côté opposé à la pièce protégée."],
    ["Sortez le pion adverse en 2 tirs avec un rebond sur le mur fixe.", "Touchez la cible après le rebond en 2 tirs.", "Utilisez d'abord le mur fixe plutôt qu'un choc direct.", "Envoyez la tour vers le mur puis touchez la cible."],
    ["Sortez les deux pions adverses en 2 tirs.", "Sortez les deux cibles en 1 tir.", "Comparez leur ligne et leur espacement.", "Reliez le premier choc à la seconde cible."],
    ["Envoyez le pion adverse dans le trou central en 3 tirs.", "Réussissez en 1 tir en gardant votre tour.", "Observez le bord du trou et la trajectoire.", "Dirigez la vitesse vers le trou central."],
    ["Sortez la tour adverse en 3 tirs en protégeant le roi.", "Sortez-la sans toucher le roi protégé.", "Trouvez un angle qui laisse la pièce protégée immobile.", "Réduisez la force et touchez seulement le côté."],
    ["Sortez les deux pions adverses en 3 tirs.", "Réussissez en 2 tirs en gardant votre fou.", "Une pièce couchée peut toujours être choisie et lancée.", "Profitez de l'angle du premier choc créé par la pose basse."],
    ["Sortez le pion adverse en 2 tirs.", "Utilisez un point central avec une force de 60% maximum.", "Le point central de la tour réduit sa rotation.", "Réglez la force affichée à 60% ou moins."],
    ["Avec le cavalier, sortez le pion adverse à travers plusieurs trous en 2 tirs.", "Réussissez en 1 tir en gardant votre cavalier.", "Le cavalier peut franchir l'obstacle devant lui.", "Choisissez d'abord un point d'atterrissage sans trou."],
    ["Sortez le pion adverse en 3 tirs sans toucher le pion protégé.", "Avec un point personnalisé, réussissez en 2 tirs en protégeant le pion.", "Changez l'approche du fou autour du pilier.", "Réglez la première rotation avec un point personnalisé."],
    ["Détruisez le mur et sortez le pion adverse en 4 tirs.", "Suivez la séquence du mur en 2 tirs en gardant votre tour.", "Vérifiez la durabilité restante du mur pour ouvrir le passage.", "Détruisez le mur au premier tir puis utilisez le passage."],
    ["Sortez les 3 pions adverses en 4 tirs en protégeant le roi.", "Sortez les trois cibles en 2 tirs en gardant le roi protégé.", "Choisissez l'ordre des cibles pour économiser des tirs.", "Trouvez un angle de chaîne qui ne revient pas vers l'allié."],
  ],
  es: [
    ["Expulsa el peón rival en 2 lanzamientos.", "Hazlo en 1 lanzamiento y conserva tu peón.", "Observa primero la dirección del objetivo.", "Empuja solo el objetivo con un golpe suave de lado."],
    ["Expulsa el alfil rival en 2 lanzamientos y protege el peón.", "Expulsa el alfil sin tocar el peón protegido.", "Comprueba el espacio libre alrededor de la pieza protegida.", "Empuja desde el lado opuesto a la pieza protegida."],
    ["Expulsa el peón rival en 2 lanzamientos usando el rebote de una pared fija.", "Golpea el objetivo tras el rebote en 2 lanzamientos.", "Usa primero la pared fija en vez de un choque directo.", "Envía la torre a la pared y golpea el objetivo tras rebotar."],
    ["Expulsa los dos peones rivales en 2 lanzamientos.", "Expulsa ambos objetivos en 1 lanzamiento.", "Compara la línea y la separación de los objetivos.", "Une el primer choque con el segundo objetivo."],
    ["Envía el peón rival al agujero central en 3 lanzamientos.", "Hazlo en 1 lanzamiento y conserva tu torre.", "Observa el borde del agujero y la línea de movimiento.", "Cambia la velocidad del objetivo hacia el agujero central."],
    ["Expulsa la torre rival en 3 lanzamientos y protege al rey.", "Expulsa la torre sin tocar al rey protegido.", "Busca un ángulo libre que mantenga quieta la pieza protegida.", "Baja la fuerza y toca solo el lateral de la pieza rival."],
    ["Expulsa los dos peones rivales en 3 lanzamientos.", "Hazlo en 2 lanzamientos y conserva tu alfil.", "Una pieza tumbada también puede seleccionarse y lanzarse.", "Aprovecha el ángulo del primer choque creado por su postura baja."],
    ["Expulsa el peón rival en 2 lanzamientos.", "Usa un golpe central con una fuerza de 60% o menos.", "El golpe central de la torre reduce la rotación.", "Ajusta la fuerza mostrada al 60% o menos."],
    ["Con el caballo, expulsa el peón rival entre varios agujeros en 2 lanzamientos.", "Hazlo en 1 lanzamiento y conserva tu caballo.", "El caballo puede saltar el obstáculo que tiene delante.", "Elige primero un punto de aterrizaje que evite los agujeros."],
    ["Expulsa el peón rival en 3 lanzamientos sin tocar el peón protegido.", "Usa un golpe personalizado, hazlo en 2 lanzamientos y protege el peón.", "Cambia la línea de entrada del alfil alrededor del pilar.", "Ajusta la primera rotación con un golpe personalizado."],
    ["Rompe la pared y expulsa el peón rival en 4 lanzamientos.", "Sigue la secuencia de pared en 2 lanzamientos y conserva tu torre.", "Comprueba la durabilidad restante de la pared para abrir el paso.", "Rompe la pared con el primer tiro y usa el camino abierto."],
    ["Expulsa los 3 peones rivales en 4 lanzamientos y protege al rey.", "Expulsa los tres objetivos en 2 lanzamientos y conserva el rey protegido.", "Elige el orden de los objetivos para ahorrar lanzamientos.", "Busca un ángulo de cadena que no rebote hacia tu aliado."],
  ],
  ru: [
    ["Сбейте пешку соперника с доски за 2 удара.", "Сделайте это за 1 удар, сохранив свою пешку.", "Сначала изучите направление цели.", "Лёгким боковым ударом толкните только цель."],
    ["Сбейте слона соперника за 2 удара, сохранив пешку.", "Сбейте слона, не коснувшись защищённой пешки.", "Сначала найдите свободное место вокруг защищённой фигуры.", "Толкайте с противоположной стороны."],
    ["Сбейте пешку соперника за 2 удара через отражение от фиксированной стены.", "Попадите в цель после отражения за 2 удара.", "Сначала используйте фиксированную стену, а не прямое столкновение.", "Отправьте ладью к стене и ударьте цель после отскока."],
    ["Сбейте обе пешки соперника за 2 удара.", "Сбейте обе цели за 1 удар.", "Сравните линию и расстояние между целями.", "После первого столкновения направьте удар к второй цели."],
    ["Отправьте пешку соперника в центральную лунку за 3 удара.", "Сделайте это за 1 удар, сохранив свою ладью.", "Наблюдайте край лунки и линию движения цели.", "Направьте скорость цели к центральной лунке."],
    ["Сбейте ладью соперника за 3 удара, сохранив короля.", "Сбейте ладью, не задев защищённого короля.", "Найдите свободный угол, не двигающий защитную фигуру.", "Снизьте силу и коснитесь только бока фигуры."],
    ["Сбейте обе пешки соперника за 3 удара.", "Сделайте это за 2 удара, сохранив своего слона.", "Лежащую фигуру тоже можно выбрать и запустить.", "Используйте угол первого столкновения, созданный низкой позой."],
    ["Сбейте пешку соперника за 2 удара.", "Используйте центральную точку и силу не более 60%.", "Центральный удар ладьи уменьшает вращение.", "Установите отображаемую силу на 60% или меньше."],
    ["Конём сбейте пешку соперника через несколько лунок за 2 удара.", "Сделайте это за 1 удар, сохранив своего коня.", "Конь может перепрыгнуть препятствие впереди.", "Сначала выберите точку приземления вдали от лунок."],
    ["Сбейте пешку соперника за 3 удара, не касаясь защищённой пешки.", "Пользуясь своей точкой удара, сделайте это за 2 удара и сохраните пешку.", "Измените линию подхода слона вокруг столба.", "Настройте первое вращение своей точкой удара."],
    ["Разрушьте стену и сбейте пешку соперника за 4 удара.", "Следуя последовательности стены, сделайте это за 2 удара и сохраните ладью.", "Проверьте прочность стены и откройте путь.", "Разрушьте стену первым ударом, затем используйте открытый путь."],
    ["Сбейте 3 пешки соперника за 4 удара, сохранив короля.", "Сбейте все три цели за 2 удара и сохраните защищённого короля.", "Выберите порядок целей, чтобы сократить число ударов.", "Найдите цепной угол, не отбрасывающий фигуру к союзнику."],
  ],
  "pt-BR": [
    ["Tire o peão adversário do tabuleiro em 2 lançamentos.", "Faça em 1 lançamento mantendo seu peão vivo.", "Observe primeiro a direção do alvo.", "Use um toque lateral leve para empurrar apenas o alvo."],
    ["Tire o bispo adversário em 2 lançamentos protegendo o peão.", "Tire o bispo sem tocar o peão protegido.", "Confira primeiro o espaço livre ao redor da peça protegida.", "Empurre pelo lado oposto à peça protegida."],
    ["Tire o peão adversário em 2 lançamentos usando o rebote na parede fixa.", "Acerte o alvo após o rebote em 2 lançamentos.", "Use a parede fixa antes de tentar uma colisão direta.", "Envie a torre à parede e acerte o alvo após o rebote."],
    ["Tire os dois peões adversários em 2 lançamentos.", "Tire os dois alvos em 1 lançamento.", "Compare a linha e o espaçamento dos alvos.", "Crie uma direção do primeiro choque até o segundo alvo."],
    ["Envie o peão adversário ao buraco central em 3 lançamentos.", "Faça em 1 lançamento mantendo sua torre viva.", "Observe a borda do buraco e a linha de movimento.", "Mude a velocidade do alvo para o buraco central."],
    ["Tire a torre adversária em 3 lançamentos protegendo o rei.", "Tire a torre sem tocar o rei protegido.", "Encontre um ângulo livre que deixe a peça protegida parada.", "Reduza a força e toque somente a lateral da peça."],
    ["Tire os dois peões adversários em 3 lançamentos.", "Faça em 2 lançamentos mantendo seu bispo vivo.", "Uma peça caída ainda pode ser escolhida e lançada.", "Use o ângulo do primeiro choque criado pela postura baixa."],
    ["Tire o peão adversário em 2 lançamentos.", "Use um ponto central com força de no máximo 60%.", "O ponto central da torre reduz a rotação.", "Ajuste a força exibida para 60% ou menos."],
    ["Com o cavalo, tire o peão adversário entre vários buracos em 2 lançamentos.", "Faça em 1 lançamento mantendo seu cavalo vivo.", "O cavalo pode saltar o obstáculo à frente.", "Escolha primeiro um ponto de pouso que evite os buracos."],
    ["Tire o peão adversário em 3 lançamentos sem tocar o peão protegido.", "Use um ponto personalizado, faça em 2 lançamentos e proteja o peão.", "Mude a linha de aproximação do bispo ao redor do pilar.", "Ajuste a primeira rotação com um ponto personalizado."],
    ["Destrua a parede e tire o peão adversário em 4 lançamentos.", "Siga a sequência da parede em 2 lançamentos mantendo sua torre viva.", "Confira a durabilidade restante da parede para abrir o caminho.", "Destrua a parede no primeiro tiro e use o caminho aberto."],
    ["Tire os 3 peões adversários em 4 lançamentos protegendo o rei.", "Tire os três alvos em 2 lançamentos mantendo o rei protegido.", "Escolha a ordem dos alvos para economizar lançamentos.", "Encontre um ângulo de cadeia que não rebata para seu aliado."],
  ],
};

const FAILURE_COPY: Record<LanguageCode, Record<string, string>> = {
  ko: {
    "no-player-pieces": "내 말이 모두 장외로 떨어졌습니다.", "forbidden-fall": "보호 대상 말이 장외로 떨어졌습니다.", "required-alive-fallen": "끝까지 살아 있어야 할 말이 장외로 떨어졌습니다.", "forbidden-contact": "접촉하면 안 되는 말과 부딪혔습니다.", "launch-budget-exceeded": "허용된 발사 횟수를 초과했습니다.", "required-hole-out-missing": "지정된 말이 구멍으로 빠지지 않았습니다.", "required-wall-destruction-missing": "필수 벽을 파괴하지 못했습니다.", "wall-destruction-order-missing": "목표가 떨어지기 전에 벽을 부수지 못했습니다.", "contact-sequence-missing": "필수 충돌 순서를 완성하지 못했습니다.", "custom-hit-missing": "필수 커스텀 타점을 사용하지 않았습니다.", "rook-shot-rule-missing": "룩의 타점 또는 세기 조건을 만족하지 못했습니다.", "required-fall-missing": "장외로 보내야 할 목표가 남아 있습니다.", "data-error": "퍼즐 데이터가 올바르지 않습니다.",
  },
  en: {
    "no-player-pieces": "All of your pieces fell off the board.", "forbidden-fall": "A protected piece fell off the board.", "required-alive-fallen": "A piece required to survive fell off the board.", "forbidden-contact": "A forbidden piece was contacted.", "launch-budget-exceeded": "The launch budget was exceeded.", "required-hole-out-missing": "The required piece did not fall through the hole.", "required-wall-destruction-missing": "The required wall was not destroyed.", "contact-sequence-missing": "The required collision sequence was not completed.", "custom-hit-missing": "The required custom strike point was not used.", "rook-shot-rule-missing": "The rook strike point or power condition was not met.", "required-fall-missing": "A required target is still on the board.", "data-error": "The puzzle data is invalid.",
  },
  ja: {
    "no-player-pieces": "自分の駒がすべて盤外へ落ちました。", "forbidden-fall": "保護対象の駒が盤外へ落ちました。", "required-alive-fallen": "生き残る必要のある駒が落ちました。", "forbidden-contact": "接触禁止の駒に触れました。", "launch-budget-exceeded": "発射回数の上限を超えました。", "required-hole-out-missing": "指定の駒が穴から落ちませんでした。", "required-wall-destruction-missing": "必要な壁を壊せませんでした。", "contact-sequence-missing": "必要な衝突順を完了できませんでした。", "custom-hit-missing": "必要なカスタム打点を使いませんでした。", "rook-shot-rule-missing": "ルークの打点または力の条件未達です。", "required-fall-missing": "盤外へ落とす目標が残っています。", "data-error": "パズルデータが正しくありません。",
  },
  "zh-CN": {
    "no-player-pieces": "己方棋子全部掉出棋盘。", "forbidden-fall": "保护棋子掉出了棋盘。", "required-alive-fallen": "必须存活的棋子掉出了棋盘。", "forbidden-contact": "碰到了禁止接触的棋子。", "launch-budget-exceeded": "超过了发射次数限制。", "required-hole-out-missing": "指定棋子没有掉入洞中。", "required-wall-destruction-missing": "没有破坏必需的墙壁。", "contact-sequence-missing": "没有完成必需的碰撞顺序。", "custom-hit-missing": "没有使用必需的自定义击打点。", "rook-shot-rule-missing": "未满足车的击打点或力度条件。", "required-fall-missing": "仍有必须弹出的目标。", "data-error": "谜题数据无效。",
  },
  de: {
    "no-player-pieces": "Alle eigenen Figuren sind vom Brett gefallen.", "forbidden-fall": "Eine geschützte Figur ist gefallen.", "required-alive-fallen": "Eine zum Überleben erforderliche Figur ist gefallen.", "forbidden-contact": "Eine verbotene Figur wurde berührt.", "launch-budget-exceeded": "Das Schusslimit wurde überschritten.", "required-hole-out-missing": "Die erforderliche Figur fiel nicht ins Loch.", "required-wall-destruction-missing": "Die erforderliche Wand wurde nicht zerstört.", "contact-sequence-missing": "Die erforderliche Kollisionsfolge wurde nicht abgeschlossen.", "custom-hit-missing": "Der erforderliche eigene Treffpunkt wurde nicht verwendet.", "rook-shot-rule-missing": "Treffpunkt oder Kraftbedingung des Turms wurde nicht erfüllt.", "required-fall-missing": "Ein erforderliches Ziel steht noch auf dem Brett.", "data-error": "Die Rätseldaten sind ungültig.",
  },
  fr: {
    "no-player-pieces": "Toutes vos pièces sont sorties du plateau.", "forbidden-fall": "Une pièce protégée est sortie du plateau.", "required-alive-fallen": "Une pièce qui devait survivre est sortie.", "forbidden-contact": "Une pièce interdite a été touchée.", "launch-budget-exceeded": "La limite de tirs a été dépassée.", "required-hole-out-missing": "La pièce requise n'est pas tombée dans le trou.", "required-wall-destruction-missing": "Le mur requis n'a pas été détruit.", "contact-sequence-missing": "La séquence de collisions requise n'est pas terminée.", "custom-hit-missing": "Le point de frappe personnalisé requis n'a pas été utilisé.", "rook-shot-rule-missing": "La condition de point ou de force de la tour n'est pas remplie.", "required-fall-missing": "Une cible requise est encore sur le plateau.", "data-error": "Les données du puzzle sont invalides.",
  },
  es: {
    "no-player-pieces": "Todas tus piezas cayeron del tablero.", "forbidden-fall": "Una pieza protegida cayó del tablero.", "required-alive-fallen": "Una pieza que debía sobrevivir cayó.", "forbidden-contact": "Tocaste una pieza cuyo contacto estaba prohibido.", "launch-budget-exceeded": "Superaste el límite de lanzamientos.", "required-hole-out-missing": "La pieza requerida no cayó por el agujero.", "required-wall-destruction-missing": "No destruiste la pared requerida.", "contact-sequence-missing": "No completaste la secuencia de colisiones requerida.", "custom-hit-missing": "No usaste el golpe personalizado requerido.", "rook-shot-rule-missing": "No cumpliste la condición de golpe o fuerza de la torre.", "required-fall-missing": "Queda un objetivo que debía caer.", "data-error": "Los datos del rompecabezas no son válidos.",
  },
  ru: {
    "no-player-pieces": "Все ваши фигуры упали с доски.", "forbidden-fall": "Защищённая фигура упала с доски.", "required-alive-fallen": "Фигура, которая должна была выжить, упала.", "forbidden-contact": "Произошло запрещённое касание.", "launch-budget-exceeded": "Превышен лимит ударов.", "required-hole-out-missing": "Нужная фигура не упала в лунку.", "required-wall-destruction-missing": "Нужная стена не разрушена.", "contact-sequence-missing": "Нужная последовательность столкновений не выполнена.", "custom-hit-missing": "Не использована нужная пользовательская точка удара.", "rook-shot-rule-missing": "Не выполнено условие точки или силы удара ладьи.", "required-fall-missing": "Нужная цель ещё на доске.", "data-error": "Данные головоломки недействительны.",
  },
  "pt-BR": {
    "no-player-pieces": "Todas as suas peças caíram do tabuleiro.", "forbidden-fall": "Uma peça protegida caiu do tabuleiro.", "required-alive-fallen": "Uma peça que deveria sobreviver caiu.", "forbidden-contact": "Uma peça proibida foi tocada.", "launch-budget-exceeded": "O limite de lançamentos foi excedido.", "required-hole-out-missing": "A peça exigida não caiu pelo buraco.", "required-wall-destruction-missing": "A parede exigida não foi destruída.", "contact-sequence-missing": "A sequência de colisões exigida não foi concluída.", "custom-hit-missing": "O ponto de ataque personalizado exigido não foi usado.", "rook-shot-rule-missing": "A condição de ponto ou força da torre não foi cumprida.", "required-fall-missing": "Ainda há um alvo que deveria cair.", "data-error": "Os dados do quebra-cabeça são inválidos.",
  },
};

const WALL_ORDER_FAILURE_COPY: Record<LanguageCode, string> = {
  ko: "목표가 떨어지기 전에 벽을 부수지 못했습니다.",
  en: "The target fell before the wall was broken.",
  ja: "壁を壊す前に目標が落ちました。",
  "zh-CN": "墙壁被破坏前目标就掉落了。",
  de: "Das Ziel fiel, bevor die Wand zerstört wurde.",
  fr: "La cible est tombée avant la destruction du mur.",
  es: "El objetivo cayó antes de romper la pared.",
  ru: "Цель упала до разрушения стены.",
  "pt-BR": "O alvo caiu antes de a parede ser destruída.",
};
for (const language of Object.keys(FAILURE_COPY) as LanguageCode[]) {
  FAILURE_COPY[language]["wall-destruction-order-missing"] = WALL_ORDER_FAILURE_COPY[language];
}

for (const language of Object.keys(PUZZLE_TEXTS) as LanguageCode[]) {
  const dictionary = PUZZLE_TEXTS[language];
  const titles = PUZZLE_TITLES[language];
  const copy = PUZZLE_COPY[language];
  for (let index = 1; index <= 12; index++) {
    const suffix = String(index).padStart(2, "0");
    dictionary[`puzzle_${suffix}_title`] = titles[index - 1];
    const detail = PUZZLE_DETAILS[language]?.[index - 1];
    dictionary[`puzzle_${suffix}_objective`] = detail?.[0] ?? copy.objective;
    dictionary[`puzzle_${suffix}_gold`] = detail?.[1] ?? copy.gold;
    dictionary[`puzzle_${suffix}_limit`] = copy.limit;
    dictionary[`puzzle_${suffix}_hint_1`] = detail?.[2] ?? copy.hint1;
    dictionary[`puzzle_${suffix}_hint_2`] = detail?.[3] ?? copy.hint2;
  }
}

export function puzzleText(key: string, params: Record<string, string | number> = {}): string {
  const language = I18nManager.getLanguage();
  const text = PUZZLE_TEXTS[language]?.[key] ?? PUZZLE_TEXTS.en[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (_match, name: string) => String(params[name] ?? `{${name}}`));
}

export function failureReason(code: string): string {
  const language = I18nManager.getLanguage();
  return FAILURE_COPY[language]?.[code] ?? FAILURE_COPY.en[code] ?? FAILURE_COPY[language]?.["data-error"] ?? FAILURE_COPY.en["data-error"];
}

export function medalText(medal: number): string {
  if (medal >= 3) return puzzleText("medal_gold");
  if (medal === 2) return puzzleText("medal_silver");
  if (medal === 1) return puzzleText("medal_bronze");
  return puzzleText("no_medal");
}
