import { I18nManager, type LanguageCode } from "./i18n";
const languages: LanguageCode[] = ["ko", "en", "ja", "zh-CN", "de", "fr", "es", "ru", "pt-BR"];
export const UI_COPY = {
 spin: ["스핀 굴절","Spin ricochet","スピン反射","旋转反弹","Drall-Abprall","Ricochet avec effet","Rebote con giro","Рикошет с вращением","Ricochete com efeito"],
 overdrive: ["오버드라이브","Overdrive","オーバードライブ","超强发射","Überantrieb","Surpuissance","Potencia extra","Усиленный удар","Potência extra"],
 board: ["ChessAlkkagi 3D 체스판","ChessAlkkagi 3D chessboard","ChessAlkkagi 3Dチェス盤","ChessAlkkagi 3D棋盘","ChessAlkkagi 3D-Schachbrett","Échiquier 3D ChessAlkkagi","Tablero 3D ChessAlkkagi","Шахматная доска 3D ChessAlkkagi","Tabuleiro 3D ChessAlkkagi"],
 strike: ["확대 타점 선택","Enlarged strike point selector","拡大打点選択","放大击球点选择","Vergrößerte Treffpunktauswahl","Sélection agrandie du point d’impact","Selector ampliado del punto de impacto","Увеличенный выбор точки удара","Seleção ampliada do ponto de impacto"],
 promotionTitle: ["폰 승급", "Pawn promotion", "ポーンの昇格", "兵升变", "Bauernumwandlung", "Promotion du pion", "Promoción del peón", "Превращение пешки", "Promoção do peão"],
 promotionHint: ["상대 진영 끝에서 살아남은 폰을 승급할 기물을 선택하세요.", "Choose a piece for the pawn that survived at the opponent’s end.", "相手側の端で生き残ったポーンの昇格先を選んでください。", "为在对方底线存活的兵选择升变棋子。", "Wähle eine Figur für den Bauern, der am gegnerischen Rand überlebt hat.", "Choisissez une pièce pour le pion ayant survécu au bord adverse.", "Elige una pieza para el peón que sobrevivió en el extremo rival.", "Выберите фигуру для пешки, выжившей на краю соперника.", "Escolha uma peça para o peão que sobreviveu na extremidade adversária."],
 Queen: ["무회전 최대 150% 직선 발사와 스핀 2.2배 굴절.", "Up to 150% straight power without spin; 2.2× spin ricochet.", "無回転で最大150%の直線発射。スピン反射角は2.2倍。", "无旋转直线发射最高150%，旋转反弹角度2.2倍。", "Bis zu 150% geradlinige Kraft ohne Drall; 2,2-facher Drall-Abprallwinkel.", "Puissance rectiligne jusqu’à 150% sans effet ; angle de ricochet avec effet ×2,2.", "Potencia recta hasta 150% sin giro; ángulo de rebote con giro ×2,2.", "Прямой удар до 150% без вращения; угол рикошета с вращением ×2,2.", "Força reta de até 150% sem efeito; ângulo de ricochete com efeito ×2,2."],
 Rook: ["무회전 직선 발사 최대 150%.", "Up to 150% straight power without spin.", "無回転の直線発射は最大150%。", "无旋转直线发射最高150%。", "Bis zu 150% geradlinige Kraft ohne Drall.", "Puissance rectiligne jusqu’à 150% sans effet.", "Potencia recta hasta 150% sin giro.", "Прямой удар до 150% без вращения.", "Força reta de até 150% sem efeito."],
 Bishop: ["스핀 충돌 시 반사 각도 2.2배.", "Spin collisions multiply the ricochet angle by 2.2.", "スピン衝突時の反射角は2.2倍。", "旋转碰撞时反弹角度为2.2倍。", "Bei Drallkollisionen wird der Abprallwinkel mit 2,2 multipliziert.", "Les collisions avec effet multiplient l’angle de ricochet par 2,2.", "Los choques con giro multiplican el ángulo de rebote por 2,2.", "При столкновении с вращением угол рикошета увеличивается в 2,2 раза.", "Colisões com efeito multiplicam o ângulo de ricochete por 2,2."],
 Knight: ["65° 포물선으로 앞 기물을 뛰어넘습니다.", "Jumps over pieces along a 65° arc.", "65°の放物線で前方の駒を飛び越えます。", "以65°抛物线跳过前方棋子。", "Springt in einem 65°-Bogen über Figuren.", "Saute par-dessus les pièces selon un arc de 65°.", "Salta sobre las piezas con un arco de 65°.", "Перепрыгивает фигуры по дуге под углом 65°.", "Salta sobre peças em um arco de 65°."],
 privacy: ["광고 개인정보 설정", "Ad privacy settings", "広告のプライバシー設定", "广告隐私设置", "Datenschutzeinstellungen für Werbung", "Confidentialité des annonces", "Privacidad de anuncios", "Конфиденциальность рекламы", "Privacidade dos anúncios"],
 preparing: ["준비 중…", "Preparing…", "準備中…", "准备中…", "Vorbereitung…", "Préparation…", "Preparando…", "Подготовка…", "Preparando…"],
 moving: ["이동 중…", "Returning…", "移動中…", "返回中…", "Rückkehr…", "Retour…", "Volviendo…", "Возврат…", "Voltando…"],
 restartFailed: ["다시 시작 실패", "Could not restart", "再開できませんでした", "无法重新开始", "Neustart fehlgeschlagen", "Impossible de recommencer", "No se pudo reiniciar", "Не удалось начать заново", "Não foi possível reiniciar"],
 menuFailed: ["메뉴 이동 실패", "Could not return to menu", "メニューに戻れませんでした", "无法返回菜单", "Rückkehr zum Menü fehlgeschlagen", "Impossible de revenir au menu", "No se pudo volver al menú", "Не удалось вернуться в меню", "Não foi possível voltar ao menu"],
 upgradeFailed: ["강화 적용 실패", "Could not apply upgrade", "強化を適用できませんでした", "无法应用强化", "Verbesserung fehlgeschlagen", "Impossible d’appliquer l’amélioration", "No se pudo aplicar la mejora", "Не удалось применить улучшение", "Não foi possível aplicar a melhoria"],
 acceleration: ["물리 가속 ({speed}×)", "Physics speed ({speed}×)", "物理演算の速度（{speed}倍）", "物理加速（{speed}倍）", "Physiktempo ({speed}×)", "Vitesse physique ({speed}×)", "Velocidad física ({speed}×)", "Скорость физики ({speed}×)", "Velocidade da física ({speed}×)"],
 swap: ["위치 변경", "Swap positions", "位置交換", "交换位置", "Positionen tauschen", "Échanger les positions", "Intercambiar posiciones", "Поменять позиции", "Trocar posições"],
 cancelSwap: ["스왑 취소", "Cancel swap", "交換をキャンセル", "取消交换", "Tausch abbrechen", "Annuler l’échange", "Cancelar intercambio", "Отменить обмен", "Cancelar troca"],
 defend: ["철벽 방어", "Iron defense", "鉄壁の防御", "铁壁防御", "Eiserne Verteidigung", "Défense de fer", "Defensa férrea", "Железная защита", "Defesa de ferro"],
 controls: ["조작 모드", "Control mode", "操作モード", "操作模式", "Steuerungsmodus", "Mode de contrôle", "Modo de control", "Режим управления", "Modo de controle"],
 actions: ["동작 선택", "Choose action", "操作を選択", "选择操作", "Aktion wählen", "Choisir une action", "Elegir acción", "Выберите действие", "Escolher ação"],
 swapHint: ["교환할 기물을 선택하세요. 빈 곳을 누르면 취소합니다.", "Select a piece to swap. Select empty space to cancel.", "交換する駒を選択してください。空白を押すとキャンセルします。", "选择要交换的棋子，点击空白处取消。", "Wähle eine Figur zum Tauschen. Klicke zum Abbrechen auf eine freie Stelle.", "Choisissez une pièce à échanger. Touchez un espace vide pour annuler.", "Elige una pieza para intercambiar. Pulsa un espacio vacío para cancelar.", "Выберите фигуру для обмена. Нажмите на пустое место для отмены.", "Escolha uma peça para trocar. Toque em um espaço vazio para cancelar."],
 remaining: ["남은 시간: {time}초", "Time remaining: {time}s", "残り時間：{time}秒", "剩余时间：{time}秒", "Verbleibende Zeit: {time}s", "Temps restant : {time}s", "Tiempo restante: {time}s", "Осталось: {time} с", "Tempo restante: {time}s"],
 launchRejected: ["발사할 수 없습니다. 다시 조준해주세요.", "Cannot launch. Please aim again.", "発射できません。もう一度狙ってください。", "无法发射，请重新瞄准。", "Abschuss nicht möglich. Bitte erneut zielen.", "Tir impossible. Visez à nouveau.", "No se puede lanzar. Vuelve a apuntar.", "Невозможно запустить. Прицельтесь снова.", "Não é possível lançar. Mire novamente."],
 powerRange: ["발사 세기는 0~{max}% 범위여야 합니다.", "Launch power must be between 0 and {max}%.", "発射の強さは0～{max}%にしてください。", "发射力度必须在0到{max}%之间。", "Die Schusskraft muss zwischen 0 und {max}% liegen.", "La puissance doit être comprise entre 0 et {max}%.", "La potencia debe estar entre 0 y {max}%.", "Сила запуска должна быть от 0 до {max}%.", "A força deve estar entre 0 e {max}%."],
 pendingLaunch: ["이미 처리 대기 중인 발사가 있습니다.", "A launch is already pending.", "すでに発射を処理中です。", "已有待处理的发射。", "Ein Abschuss steht bereits aus.", "Un tir est déjà en attente.", "Ya hay un lanzamiento pendiente.", "Запуск уже ожидает обработки.", "Já existe um lançamento pendente."],
 elevation: ["고도", "Elevation", "仰角", "仰角", "Höhenwinkel", "Élévation", "Elevación", "Угол возвышения", "Elevação"],
 pitch: ["피치", "Pitch", "俯仰角", "俯仰角", "Neigung", "Inclinaison", "Inclinación", "Наклон", "Inclinação"],
 power: ["세기", "Power", "強さ", "力度", "Stärke", "Puissance", "Potencia", "Сила", "Força"],
 connectionHelp: ["연결을 확인하고 다시 시도해 주세요.", "Check your connection and try again.", "接続を確認して、もう一度お試しください。", "请检查连接后重试。", "Prüfe deine Verbindung und versuche es erneut.", "Vérifiez votre connexion et réessayez.", "Comprueba la conexión e inténtalo de nuevo.", "Проверьте подключение и повторите попытку.", "Verifique sua conexão e tente novamente."],
} satisfies Record<string, readonly [string,string,string,string,string,string,string,string,string]>;
export function uiText(key: keyof typeof UI_COPY, params: Record<string, string | number> = {}): string {
 return UI_COPY[key][languages.indexOf(I18nManager.getLanguage())]!.replace(/\{(\w+)\}/g, (match, name: string) => String(params[name] ?? match));
}
